### ISSUE TITLE
pyRevit - copy & pasteVP not working

### ISSUE THREAD

**Issue by ossfuego** [eirannejad/pyRevit#1001]
Help, I keep getting an error when trying to use these functions in pyRevit plus. see below.
  
I select the view port and then click on copyVP in pyRevitplus:

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\o*******\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension\pyRevitPlus.tab\ViewPorts.panel\ViewportPlacement.stack3\CopyVP.pushbutton\script.py", line 57, in <module>
 File "pickle.py", line 1376, in dump
 File "pickle.py", line 286, in save
 File "pickle.py", line 752, in save_global
 File "pickle.py", line 224, in dump
 File "pickle.py", line 331, in save
 File "pickle.py", line 401, in save_reduce
 File "pickle.py", line 286, in save
 File "pickle.py", line 568, in save_tuple
pickle.PicklingError: Can't pickle <class 'namedtuple_Point.Point'>: it's not found as namedtuple_Point.Point

Script Executor Traceback:
System.Exception: Can't pickle <class 'namedtuple_Point.Point'>: it's not found as namedtuple_Point.Point
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

Same with PasteVP:

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\o*******\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension\pyRevitPlus.tab\ViewPorts.panel\ViewportPlacement.stack3\PasteVP.pushbutton\script.py", line 43, in <module>
 File "pickle.py", line 1384, in load
 File "pickle.py", line 864, in load
 File "pickle.py", line 886, in load_eof
EOFError

Script Executor Traceback:
System.IO.EndOfStreamException: EOFError
 at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
 at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

Thank you.

**Comment by eirannejad** [comment]
Please report the issue here: https://github.com/gtalarico/pyrevitplus

This is related to a pyRevit extension and not the core
