### ISSUE TITLE
Error message on COPY/MOVE SELECTED VIEWPORTS TO SELECTED SHEETS

### ISSUE THREAD

**Issue by BRigney189** [eirannejad/pyRevit#1028]
COPY SELECTED VIEWPORTS TO SELECTED SHEETS:

```
IronPython Traceback:
Traceback (most recent call last):
File "C:\Users\ky.vong\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Sheets.pulldown\Copy Selected Viewports To Selected Sheets.pushbutton\script.py", line 46, in <module>
File "C:\Users\ky.vong\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 1723, in select_sheets
Exception: Failed to get views.


Script Executor Traceback:
Autodesk.Revit.Exceptions.InvalidOperationException: Failed to get views.
at Microsoft.Scripting.Interpreter.MethodInfoCallInstruction.InvokeWorker(Object[] args)
at Microsoft.Scripting.Interpreter.MethodInfoCallInstruction.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.LightLambda.Run6[T0,T1,T2,T3,T4,T5,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
at Microsoft.Scripting.Interpreter.DynamicInstruction`6.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

MOVE SELECTED VIEWPORTS TO SELECTED SHEET

```
IronPython Traceback:
Traceback (most recent call last):
File "C:\Users\ky.vong\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Sheets.pulldown\Move Selected Viewports To Selected Sheet.pushbutton\script.py", line 15, in <module>
File "C:\Users\ky.vong\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 1723, in select_sheets
Exception: Failed to get views.

Script Executor Traceback:
Autodesk.Revit.Exceptions.InvalidOperationException: Failed to get views.
at Microsoft.Scripting.Interpreter.MethodInfoCallInstruction.InvokeWorker(Object[] args)
at Microsoft.Scripting.Interpreter.MethodInfoCallInstruction.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.LightLambda.Run8[T0,T1,T2,T3,T4,T5,T6,T7,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
at System.Dynamic.UpdateDelegates.UpdateAndExecute7[T0,T1,T2,T3,T4,T5,T6,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
at Microsoft.Scripting.Interpreter.DynamicInstruction`8.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**Comment by eirannejad** [comment]
Testing under pyRevit 4.8.5 on Revit 2020 and can not replicate the issue. Please describe the steps or sample file that causes the issue. Note that you can not copy model or detail views between sheets as they can only be placed on a single sheet. Legends can be copied
