### ISSUE TITLE
Unable to add URL as source for extensions

### ISSUE THREAD

**Issue by guusgooskens** [eirannejad/pyRevit#1118]
**Describe the bug**

[As outlined in the wiki](https://www.notion.so/Manage-pyRevit-extensions-fa853768e94240b5b59803e5d7171be3#4eb8c8f8683f4cb6a8f5124ea09fd522), one could either pass a path or URL as source.
However, adding an URL throws an error. Not the example given, nor with a custom URL it's working.

**To Reproduce**
`pyrevit extensions sources add "https://github.com/eirannejad/pyRevit/blob/master/extensions/extensions.json"`

Thrown error in the CLI:
```
Error: The given path's format is not supported. (System.NotSupportedException)
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at pyRevitLabs.Common.Extensions.StringExtensions.NormalizeAsPath(String path)
   at pyRevitLabs.PyRevit.PyRevitExtensions.RegisterExtensionLookupSource(String extLookupSource)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)
```
**Expected behavior**
Running this command should update the .ini file with the URL as a new source.

**Desktop (please complete the following information):**
 - OS: Windows 10

`pyrevit env`

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.4" | Path: "C:\Users\Guus.Gooskens\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2020.2.2" | Engine: 277 | Path: "C:\Users\Guus.Gooskens\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Guus.Gooskens\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\Guus.Gooskens\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Guus.Gooskens\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2018.3.3 Security Fix" | Engine: 277 | Path: "C:\Users\Guus.Gooskens\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Guus.Gooskens\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
master | Product: "2017.2.5 Security Fix" | Engine: 277 | Path: "C:\Users\Guus.Gooskens\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Guus.Gooskens\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Guus.Gooskens\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Code\gitlab\bim-to-bam
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
C:\Temp\extensions.json
==> Installed Revits
2020.2.2 | Version: 20.2.20.31 | Build: 20200426_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
==> Running Revit Instances
PID: 540 | 2020.2.2 | Version: 20.2.20.31 | Build: 20200426_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
PID: 9632 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: GLOBAL\Guus.Gooskens
Active User: GLOBAL\Guus.Gooskens
Admin Access: No
%APPDATA%: "C:\Users\Guus.Gooskens\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.6.2 v4.7 v4.7.1 v4.7.2 v4.8 v4.X
Installed .Net-Core Target Packs: v3.1.202
pyRevit CLI 4.8.4.0
```

**Comment by eirannejad** [comment]
Fixed and will be pushed with then net release soon
