### ISSUE TITLE
Document Data File in Hooks not using event Doc

### ISSUE THREAD

**Issue by alexdaversa** [eirannejad/pyRevit#1165]
Are temporary data files available within hooks? Specifically document data files.

My script looks something like so, following the guidance on [Python Script Facilities](https://www.notion.so/Python-Script-Facilities-dcaf1e4660134974ba69e023b3714ddc):
```python
datafile = script.get_document_data_file('doc_data_file','pym', EXEC_PARAMS.event_args.Document)
with open(datafile, 'w') as f:
	f.write(somedata)
```

It doesn't appear that the current implementation of document data files takes the document as an argument, but also that when calling ProjectInfo in revit/db/__init__.py that the newly opened document isn't available yet, or isn't able to see the document object in the hook.

Error message below:

```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\adaversa\Documents\Git\pyKSS-local\pyKSS.extension\hooks\doc-opened.py", line 15, in <module>
 File "C:\Users\adaversa\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\script.py", line 314, in get_document_data_file
 File "C:\Users\adaversa\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\revit\db\__init__.py", line 281, in filename
 File "C:\Users\adaversa\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\revit\db\__init__.py", line 277, in path
AttributeError: 'NoneType' object has no attribute 'PathName'


Script Executor Traceback:
System.MissingMemberException: 'NoneType' object has no attribute 'PathName'
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Runtime.PythonProperty.__get__(CodeContext context, Object instance, Object owner)
 at IronPython.Runtime.PythonProperty.TryGetValue(CodeContext context, Object instance, PythonType owner, Object& value)
 at IronPython.Runtime.Types.GetMemberDelegates.SlotOnly(CallSite site, Object self, CodeContext context)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Runtime.PythonProperty.__get__(CodeContext context, Object instance, Object owner)
 at IronPython.Runtime.PythonProperty.TryGetValue(CodeContext context, Object instance, PythonType owner, Object& value)
 at IronPython.Runtime.Types.GetMemberDelegates.SlotOnly(CallSite site, Object self, CodeContext context)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**Comment by alexdaversa** [comment]
Ehsan, just want to follow up--I opened the view-activated.py example hook file which contains some code to log a hook. Is this the 'official' method of saving log files within a hook script? If so, it may make sense to expose some of the document-specific pieces of the document data file to help organize hook execution by revit file.

**Comment by eirannejad** [comment]
@alexdaversa No that's a test logger internal to the hooks example extension that I use for testing. Let me fix the error above for this release and we'll look into the hooks more. Sorry for the late replies. :/

**Comment by eirannejad** [comment]
Fixed and will be published with next release
