### ISSUE TITLE
Error: Sequence contains no Elements when trying to 'Attach'

### ISSUE THREAD

**Issue by jrostarHED** [eirannejad/pyRevit#1227]
**Describe the bug**
Unable to attach pyRevit to the Revit versions that are installed.

We have tried the following CLI Commands:

pyrevit attach main latest --installed --allusers
pyrevit attach main 277 --installed --allusers
pyrevit attach main IPY2710 --installed --allusers
pyrevit attach main 2710 --installed --allusers

Each time we received the following error:

Error: Sequence contains no elements
Run with "--dbug" option to see debug messages

No .addin manifests are being generated.

**Expected behavior**
Expecting pyRevit to generate the .addin manifest and load within Revit

**Screenshots**

![image](https://user-images.githubusercontent.com/68887282/115586703-7cf09a80-a292-11eb-846b-3dfa35612a45.png)

`Debug`

````<clone_name> = main
attach = True
latest = True
--installed = True
--allusers = True
Debug: Checking for all: wiki
Debug: Missing: wiki
Debug: Checking for all: blog
Debug: Missing: blog
Debug: Checking for all: docs
Debug: Missing: docs
Debug: Checking for all: source
Debug: Missing: source
Debug: Checking for all: youtube
Debug: Missing: youtube
Debug: Checking for all: support
Debug: Missing: support
Debug: Checking for all: env
Debug: Missing: env
Debug: Checking for all: update
Debug: Missing: update
Debug: Checking for all: clone
Debug: Missing: clone
Debug: Checking for all: clones
Debug: Missing: clones
Debug: Checking for all: attach
Debug: Try getting config as dict "environment:clones"
Debug: Try getting config "environment:clones"
Debug: Config "environment:clones" = "{"main":"C:\\pyRevit\\main"}"
Debug: Normalized as "C:\pyRevit\main"
Debug: Searching for valid clones above: C:\pyRevit\main
Debug: Normalized as "C:\pyRevit\main"
Debug: Checking pyRevit clone validity "C:\pyRevit\main"
Debug: Checking clone validity by directory structure...
Debug: Normalized as "C:\pyRevit\main\pyrevitlib"
Debug: Normalized as "C:\pyRevit\main\pyrevitlib\pyrevit"
Debug: Checking pyRevit path "C:\pyRevit\main\pyrevitlib\pyrevit"
Debug: Checking clone validity by git repo...
Debug: Valid pyRevit clone "C:\pyRevit\main"
Debug: Valid clone found at: C:\pyRevit\main
Debug: Normalized as "C:\pyRevit\main"
Debug: Normalized as "C:\pyRevit\main"
Debug: Checking pyRevit clone validity "C:\pyRevit\main"
Debug: Checking clone validity by directory structure...
Debug: Normalized as "C:\pyRevit\main\pyrevitlib"
Debug: Normalized as "C:\pyRevit\main\pyrevitlib\pyrevit"
Debug: Checking pyRevit path "C:\pyRevit\main\pyrevitlib\pyrevit"
Debug: Checking clone validity by git repo...
Debug: Valid pyRevit clone "C:\pyRevit\main"
Debug: Verified clone "main=C:\pyRevit\main"
Debug: Updating config "environment:clones = {"main":"C:\\pyRevit\\main"}"
Debug: Saving config file "C:\Users\deploy-it2\AppData\Roaming\pyRevit\pyRevit_config.ini"
Debug: Attaching on latest engine...
Debug: Engine configuration found: IPY273
Debug: "kernel" : "IronPython"
Debug: "version" : "273"
Debug: "runtime" : "true"
Debug: "path" : "bin\engines\IPY273"
Debug: "assembly" : "pyRevitLoader.dll"
Debug: "description" : "IronPython Engine"
Debug: Error parsing clone "C:\pyRevit\main" engines configs from "C:\pyRevit\main\PyRevitfile" | No row with key 'compatproducts' exists in this TOML table.
Error: Sequence contains no elements (System.InvalidOperationException)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at pyRevitCLI.PyRevitCLICloneCmds.AttachClone(String cloneName, Boolean latest, Boolean dynamoSafe, String engineVersion, String revitYear, Boolean installed, Boolean attached, Boolean allUsers)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)
````

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

````==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
main | Deploy: "base" | Branch: "master" | Version: "4.8.7" | Path: "C:\pyRevit\main"
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\deploy-it2\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2020 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: HED\deploy-it2
Active User: HED\MHironaka
Admin Access: Yes
%APPDATA%: "C:\Users\deploy-it2\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.25.0.0
````

**Additional context**

**Comment by eirannejad** [comment]
Seems like you are using a very old version of CLI `pyRevit CLI 0.25.0.0`

recent is here https://github.com/eirannejad/pyRevit/releases/tag/cli-v4.8.7
