### ISSUE TITLE
Isolate "Is Painted" error

### ISSUE THREAD

**Issue by mcb-cadbim** [eirannejad/pyRevit#1240]
**Describe the bug**
Get the following error message when using the Isolate "Painted Element" tool in any standard view.

```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\morganb\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Selection.panel\select.stack\Isolate.pushbutton\script.py", line 127, in <module>
 File "C:\Users\morganb\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Selection.panel\select.stack\Isolate.pushbutton\script.py", line 119, in ask_for_options
 File "C:\Users\morganb\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Selection.panel\select.stack\Isolate.pushbutton\script.py", line 62, in get_isolation_elements
AttributeError: 'List[ElementId]' object has no attribute 'Append'


Script Executor Traceback:
System.MissingMemberException: 'List[ElementId]' object has no attribute 'Append'
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

```

**To Reproduce**
1. Open the Autodesk sample "rac_basic_sample_project.rvt"
2. Go to a 3D view
3. Run the Isolate tool and choose "Painted Element"

**Expected behavior**
Should isolate and hide all other elements

**Desktop (please complete the following information):**
 - OS: Win10 Pro
 - pyRevit Version 4.8.7 and 4.8.4
 - pyRevit Environment:

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.7" | Path: "C:\Users\morganb\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\morganb\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\morganb\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Users\morganb\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2019" | Engine: IPY277 (277) | Path: "C:\Users\morganb\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\morganb\AppData\Roaming\pyRevit-Master"
master | Product: "2017.2.5 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\morganb\AppData\Roaming\pyRevit-Master"
master | Product: "2016.1.9 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\morganb\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
pyRevitTools | Type: UIExtension | Repo: "" | Installed: "\\SDI-FS\Projects\CADBIM Support\Revit\Support\pyRevit\Extensions\TESTING\pyRevit\pyRevitTools.extension"
SHEA | Type: Unknown | Repo: "" | Installed: "\\SDI-FS\Projects\CADBIM Support\Revit\Support\pyRevit\Extensions\TESTING\SHEA\SHEA.extension"
==> Default Extension Search Path
C:\Users\morganb\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
\\SDI-FS\Projects\CADBIM Support\Revit\Support\pyRevit\Extensions\TESTING\SHEA
\\SDI-FS\Projects\CADBIM Support\Revit\Support\pyRevit\Extensions\TESTING\pyRevit
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2022 | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.30.74 | Build: 20210426_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.40.65 | Build: 20210420_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
Autodesk Revit 2019 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
2016.1.9 Security Fix | Version: 16.0.1218.0 | Build: 20190508_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
```

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by mcb-cadbim** [comment]
Thank-you

**Comment by linaspasiaura** [comment]
Hi, I wanted to ask why I can't find the"Make pattern" function but I can find the "Select pattern to export" function. Thanks for the reply.
![image](https://user-images.githubusercontent.com/96527921/147150253-75ce3124-eaf2-4e77-a051-4af244fb94b3.png)
