### ISSUE TITLE
Target file is not optional when using run command on the CLI

### ISSUE THREAD

**Issue by mda-hdm** [eirannejad/pyRevit#1290]
Hello,

I'm trying to run some unit tests for a pyRevit extension on the CLI. The tests create a fresh model programatically when running in order to create a clean and predictable environment for the tests. However I have difficulties to actually run a script without specifying a target model. According to the help of the `run` command, the `model_file` argument is optional but whenever I try to run just a Python file, I get the following error:

    Error: Model does not exist at ""

**To Reproduce**
To reproduce the error, just run the `run` command without a Revit file:

    pyrevit run script.py

**Expected behavior**
The expected behavior would be from my point of view as described on the Notion page. So the script would just run in the context of an empty Revit instance without any model paths attached.

**Comment by mda-hdm** [comment]
Hi, is there any progress on this one?

**Comment by olalancette** [comment]
The error thrown by pyrevit cli is this one :
```
>>> pyrevit run thisiscommandname --revit=2021 --debug
[...]
... Debug: Checking for all: run
... Debug: Checking for all: commands
... Debug: Missing: commands
... Error: Model does not exist at "" (System.Exception)
...    at pyRevitCLI.PyRevitCLIRevitCmds.RunExtensionCommand(String commandName, String targetFile, String revitYear, PyRevitRunnerOptions runOptions, Boolean targetIsFileList)
...    at pyRevitCLI.PyRevitCLI.ProcessArguments()
...    at pyRevitCLI.PyRevitCLI.Main(String[] args)
```

It seams to be here that it misses the "it's okay without models" : 
https://github.com/eirannejad/pyRevit/blob/b074f295861b617054c2ad1f6071bba50c885181/dev/pyRevitLabs/pyRevitCLI/PyRevitCLIRevitCmds.cs#L167-L183

Also, in the `RunExtensionCommand` , it seams that it cannot correctly parse `revitVersionNumber` from model (may be because of the french version of the parsed xml 🤷‍♂️) :
```
>>> pyrevit run thisiscommandname "C:\Users\olalancette\Desktop\Revit2021.rvt" --revit=2021 --debug
[...]
... Debug: Parsing ProjctInformation Data: "<?xml version="1.0" encoding="UTF-8"?>
... <entry xmlns="http://www.w3.org/2005/Atom" xmlns:A="urn:schemas-autodesk-com:partatom"><title>Revit2021</title> <updated>2022-08-09T09:27:00Z</updated><A:taxonomy><term>adsk:revit</term><label>Autodesk Revit</label></A:taxonomy><A:taxonomy><term>adsk:revit:grouping</term><label>Autodesk Revit Grouping</label></A:taxonomy><link rel="design-2d" type="application/rvt" href="."><A:design-file><A:title>Revit2021.rvt</A:title><A:product>Revit</A:product><A:product-version>2021</A:product-version><A:updated>2022-08-09T09:27:00Z</A:updated></A:design-file></link><A:features><A:feature><A:title>Project Information</A:title><A:group><A:title>Données d'identification</A:title></A:group><A:group><A:title>Analyse d'énergie</A:title></A:group><A:group><A:title>Analyse du trajet</A:title></A:group><A:group><A:title>Autre</A:title></A:group></A:feature></A:features></entry>
... "
... Debug: Attempting to read "PartAtom" stream from structured storage file at "C:\Users\olalancette\Desktop\Revit2021.rvt"
... Debug: Found CF Root: [-1,0,-1] Root Entry
... Error: Can not detect the Revit version of model at "C:\Users\olalancette\Desktop\Revit2021.rvt". Model might be newer than specified version 2021. (System.Exception)
...    at pyRevitCLI.PyRevitCLIRevitCmds.RunExtensionCommand(String commandName, String targetFile, String revitYear, PyRevitRunnerOptions runOptions, Boolean targetIsFileList)
...    at pyRevitCLI.PyRevitCLI.ProcessArguments()
...    at pyRevitCLI.PyRevitCLI.Main(String[] args)
```
