### ISSUE TITLE
ImportError: cannot import _usd from pxr.Usd

### ISSUE THREAD

**Issue by harrymattison** [eirannejad/pyRevit#1305]
Getting a "cannot import" error when I run a command through pyRevit
The same command runs fine from the Command Prompt
I have added the `pxr` and `usd` folders to the `lib` folder

Steps to reproduce
- Unzip files in https://drive.google.com/file/d/1_aHVvO5g2bBtpgVjS2X8QQGS1PJ9gM3X/view?usp=sharing to your pyRevit folder (in my case, C:\Users\harry\Documents\MyExtensions\MyFirstExtension.extension)
- Start Revit and run the "USD Command" in the MyTest tab

Successfully running the command from the Command Prompt
```
C:\Users\harry\Documents\GitHub\USD\extras\usd\tutorials\helloWorld>cd C:\Users\harry\Documents\MyExtensions\MyFirstExtension.extension\MyTest.tab\Tools.panel\USD Command.pushbutton

C:\Users\harry\Documents\MyExtensions\MyFirstExtension.extension\MyTest.tab\Tools.panel\USD Command.pushbutton>python script.py
HelloWorld.usda created
```

Error message when I run the command
```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\harry\Documents\MyExtensions\MyFirstExtension.extension\MyTest.tab\Tools.panel\USD Command.pushbutton\script.py", line 1, in <module>
 File "C:\Users\harry\Documents\MyExtensions\MyFirstExtension.extension\MyTest.tab\Tools.panel\lib\pxr\Usd\__init__.py", line 24, in <module>
ImportError: cannot import _usd from pxr.Usd

Script Executor Traceback:
IronPython.Runtime.Exceptions.ImportException: cannot import _usd from pxr.Usd
 at IronPython.Runtime.Importer.ImportNestedModule(CodeContext context, PythonModule module, String[] parts, Int32 current, List path)
 at IronPython.Runtime.Importer.ImportFrom(CodeContext context, Object from, String name)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
```
 - OS: Windows 10
 - pyRevit Version 4.8.8
 - pyRevit Environment: 
 ```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.8" | Path: "C:\Users\harry\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2022 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\harry\AppData\Roaming\pyRevit-Master"
master | Product: "2021.1.3" | Engine: IPY277 (277) | Path: "C:\Users\harry\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
MyFirstExtension | Type: Unknown | Repo: "" | Installed: "C:\Users\harry\Documents\MyExtensions\MyFirstExtension.extension"
==> Default Extension Search Path
C:\Users\harry\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\harry\Documents\MyExtensions\MyFirstExtension.extension
C:\Users\harry\Documents\MyExtensions
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.3 | Version: 21.1.30.74 | Build: 20210426_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: DESKTOP-GJD9Q66\harry
Active User: DESKTOP-GJD9Q66\harry
Admin Access: No
%APPDATA%: "C:\Users\harry\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7 v4.7.2 v4.8 v4.X
Installed .Net-Core Target Packs: v3.1.404 v5.0.302
pyRevit CLI 4.8.8.0
```

**Comment by htlcnn** [comment]
Please try using CPython for your script by adding this line first:
```
#! python3
```
Docs here: https://www.notion.so/Create-Your-First-CPython-Command-b8a7718c554645d1a18454c0b363e3c9

**Comment by harrymattison** [comment]
I added that line and now the error is:
```
CPython Traceback:
ImportError : DLL load failed while importing _usd: The specified module could not be found.
 File "C:\Users\harry\Documents\MyExtensions\MyFirstExtension.extension\MyTest.tab\Tools.panel\USD Command.pushbutton\script.py", line 3, in <module>
from pxr import Usd, UsdGeom
 File "C:\Users\harry\Documents\MyExtensions\MyFirstExtension.extension\MyTest.tab\Tools.panel\lib\pxr\Usd\__init__.py", line 24, in <module>
 from . import _usd

pyRevitLabs.PythonNet
at Python.Runtime.Runtime.CheckExceptionOccurred()
 at Python.Runtime.PyScope.Exec(String code, IntPtr _globals, IntPtr _locals)
 at PyRevitLabs.PyRevit.Runtime.CPythonEngine.Execute(ScriptRuntime& runtime)
```

The file __init__.py is:
```
from . import _usd
from pxr import Tf
Tf.PrepareModule(_usd, locals())
del Tf

try:
    from . import __DOC
    __DOC.Execute(locals())
    del __DOC
except Exception:
    pass
```

and that folder contains a `_usd.pyd` file

**Comment by ErikFrits** [comment]
Try adding empty __init__.py files in lib and every child folder. I could not see them in your folder structure.

https://docs.python.org/3/reference/import.html#regular-packages

**Comment by htlcnn** [comment]
I could not find any `_usd` name binding in the code base either.

**Comment by eirannejad** [comment]
Seems like the `usd` module required a native dll to run. Take a look at the module source code and see what other native libraries are referenced and need to be loaded.
