### ISSUE TITLE
Failed export of schedules to CSV

### ISSUE THREAD

**Issue by RichardPinka** [eirannejad/pyRevit#1394]
**Describe the bug**

**To Reproduce**
1. Go to schecules
2. Click on export schedules to CSV
3. select the directory where to save
4. select the particular shedules to export

**Expected behavior**
it should export CSV files from schedules ?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10 
 - pyRevit Version  v4.8.8   installed on Revit 2019
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "2021.1.3" | Manifest: "C:\Users\richa\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
Unknown | Product: "2019.2.2 Hotfix" | Manifest: "C:\Users\richa\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\richa\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021.1.3 | Version: 21.1.30.74 | Build: 20210426_1515(x64) | Language: 1033 | Path: "Revit 2021\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 47892 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: DESKTOP-Q9TJA9B\admin
Active User: DESKTOP-Q9TJA9B\admin
Admin Access: Yes
%APPDATA%: "C:\Users\richa\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.8.0

**Additional context**
ERROR MESAGE WITHIN REVIT PYREVIT ERROR MESSAGES WINDOW:

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\richa\AppData\Roaming\pyRevit_git\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\views.stack\Schedules.pulldown\Export Schedules To CSV.pushbutton\script.py", line 78, in <module>
AttributeError: 'module' object has no attribute 'correct_revittxt_encoding'

Script Executor Traceback:
System.MissingMemberException: 'module' object has no attribute 'correct_revittxt_encoding'
 at IronPython.Runtime.Operations.PythonOps.ObjectGetAttribute(CodeContext context, Object o, String name)
 at IronPython.Runtime.PythonModule.__getattribute__(CodeContext context, String name)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by RichardPinka** [comment]
Hello again, 
I tried to  re-install pyRevit, 
the result is the same.. batch exporting of scheduels to csv is not working :(

i fordot to mention after step 3  pyrevit asks me _: Regional settings list separator is ";"   Do you want to use this instead of comma ?   but wheter i choose Yes or No, there is same result
