### ISSUE TITLE
Create schedule from csv inconsistent

### ISSUE THREAD

**Issue by anjseattle** [eirannejad/pyRevit#1467]
I can successfully create a schedule from one csv file but not another, and the two csv files seem to be set up exactly the same. I get a traceback when I try the one that doesn't work:

```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\anjal\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\views.stack\Schedules.pulldown\Create Schedule from CSV.pushbutton\script.py", line 344, in <module>
 File "C:\Users\anjal\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\views.stack\Schedules.pulldown\Create Schedule from CSV.pushbutton\script.py", line 309, in read_csv_typed_data
 File "codecs.py", line 699, in next
 File "codecs.py", line 630, in next
 File "codecs.py", line 545, in readline
 File "codecs.py", line 492, in read
UnicodeDecodeError: ('unknown', u'\x85', 57, 58, '')


Script Executor Traceback:
System.Text.DecoderFallbackException: failed to decode bytes at index: 57
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**Comment by anjseattle** [comment]
Thank you!! I can figure that out. My next step was to ask my 18-year old - who knows Python, unlike me.

**Comment by eirannejad** [comment]
Ok great. Closing this then. Feel free to open back if the problem persists.

**Comment by anjseattle** [comment]
NB: I discovered that the csv file was wrapping text and once I selected all cells and unwrapped text it worked like a charm.
