### ISSUE TITLE
Invalid Path using clone / pyrevit CLI

### ISSUE THREAD

**Issue by jrostar** [eirannejad/pyRevit#1471]
**Describe the bug**
Was attempting to install pyrevit cli / pyrevit on a new computer. When running the clone command, I received the following error (Illegal characters in path) w/ debug.

It seems that the CLI is not 'seeing' the clone download in the folder and keeps 'rebuilding' the folder pathing, resulting in a c: path instead of c:\

I ended up manually installing normal pyrevit instead of using CLI.

```
clone = True
<clone_name> = main
<deployment_name> = base
--dest = C:\pyRevit\main"
Debug: Checking for all: wiki 
Debug: Missing: wiki 
Debug: Checking for all: blog 
Debug: Missing: blog 
Debug: Checking for all: docs 
Debug: Missing: docs 
Debug: Checking for all: source 
Debug: Missing: source 
Debug: Checking for all: youtube 
Debug: Missing: youtube 
Debug: Checking for all: support 
Debug: Missing: support 
Debug: Checking for all: env 
Debug: Missing: env 
Debug: Checking for all: update 
Debug: Missing: update 
Debug: Checking for all: clone 
Debug: Image file is "https://github.com/eirannejad/pyRevit/archive/master.zip" 
Debug: Destination path determined as "C:\pyRevit\main"" 
Debug: Downloading package "https://github.com/eirannejad/pyRevit/archive/master.zip" to "C:\Users\DEPLOY~3\AppData\Local\Temp\master.zip" 
Debug: Downloading "https://github.com/eirannejad/pyRevit/archive/master.zip" 
Debug: Downloaded to "C:\Users\DEPLOY~3\AppData\Local\Temp\master.zip" 
Debug: Deleting existing temp staging path "C:\Users\DEPLOY~3\AppData\Local\Temp\master" 
Debug: Recursive deleting directory "C:\Users\DEPLOY~3\AppData\Local\Temp\master" 
Debug: Staging package to "C:\Users\DEPLOY~3\AppData\Local\Temp\master" 
Debug: Searching for valid clones above: C:\Users\DEPLOY~3\AppData\Local\Temp\master 
Debug: Normalizing "C:\Users\DEPLOY~3\AppData\Local\Temp\master" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\master" 
Debug: Checking pyRevit clone validity "C:\Users\deploy-it2\AppData\Local\Temp\master" 
Debug: Checking clone validity by directory structure... 
Debug: Normalizing "C:\Users\deploy-it2\AppData\Local\Temp\master\pyrevitlib" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\master\pyrevitlib" 
Debug: Normalizing "C:\Users\deploy-it2\AppData\Local\Temp\master\pyrevitlib\pyrevit" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\master\pyrevitlib\pyrevit" 
Debug: Checking pyRevit path "C:\Users\deploy-it2\AppData\Local\Temp\master\pyrevitlib\pyrevit" 
Debug: Invalid pyRevit clone. | Path "C:\Users\deploy-it2\AppData\Local\Temp\master" is not a valid git pyRevit clone. 
Debug: Normalizing "C:\Users\DEPLOY~3\AppData\Local\Temp" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp" 
Debug: Checking pyRevit clone validity "C:\Users\deploy-it2\AppData\Local\Temp" 
Debug: Checking clone validity by directory structure... 
Debug: Normalizing "C:\Users\deploy-it2\AppData\Local\Temp\pyrevitlib" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\pyrevitlib" 
Debug: Normalizing "C:\Users\deploy-it2\AppData\Local\Temp\pyrevitlib\pyrevit" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\pyrevitlib\pyrevit" 
Debug: Checking pyRevit path "C:\Users\deploy-it2\AppData\Local\Temp\pyrevitlib\pyrevit" 
Debug: Invalid pyRevit clone. | Path "C:\Users\deploy-it2\AppData\Local\Temp" is not a valid git pyRevit clone. 
Debug: Normalizing "C:\Users\DEPLOY~3\AppData\Local" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local" 
Debug: Checking pyRevit clone validity "C:\Users\deploy-it2\AppData\Local" 
Debug: Checking clone validity by directory structure... 
Debug: Normalizing "C:\Users\deploy-it2\AppData\Local\pyrevitlib" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\pyrevitlib" 
Debug: Normalizing "C:\Users\deploy-it2\AppData\Local\pyrevitlib\pyrevit" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\pyrevitlib\pyrevit" 
Debug: Checking pyRevit path "C:\Users\deploy-it2\AppData\Local\pyrevitlib\pyrevit" 
Debug: Invalid pyRevit clone. | Path "C:\Users\deploy-it2\AppData\Local" is not a valid git pyRevit clone. 
Debug: Normalizing "C:\Users\DEPLOY~3\AppData" 
Debug: Normalized as "C:\Users\deploy-it2\AppData" 
Debug: Checking pyRevit clone validity "C:\Users\deploy-it2\AppData" 
Debug: Checking clone validity by directory structure... 
Debug: Normalizing "C:\Users\deploy-it2\AppData\pyrevitlib" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\pyrevitlib" 
Debug: Normalizing "C:\Users\deploy-it2\AppData\pyrevitlib\pyrevit" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\pyrevitlib\pyrevit" 
Debug: Checking pyRevit path "C:\Users\deploy-it2\AppData\pyrevitlib\pyrevit" 
Debug: Invalid pyRevit clone. | Path "C:\Users\deploy-it2\AppData" is not a valid git pyRevit clone. 
Debug: Normalizing "C:\Users\DEPLOY~3" 
Debug: Normalized as "C:\Users\deploy-it2" 
Debug: Checking pyRevit clone validity "C:\Users\deploy-it2" 
Debug: Checking clone validity by directory structure... 
Debug: Normalizing "C:\Users\deploy-it2\pyrevitlib" 
Debug: Normalized as "C:\Users\deploy-it2\pyrevitlib" 
Debug: Normalizing "C:\Users\deploy-it2\pyrevitlib\pyrevit" 
Debug: Normalized as "C:\Users\deploy-it2\pyrevitlib\pyrevit" 
Debug: Checking pyRevit path "C:\Users\deploy-it2\pyrevitlib\pyrevit" 
Debug: Invalid pyRevit clone. | Path "C:\Users\deploy-it2" is not a valid git pyRevit clone. 
Debug: Normalizing "C:\Users" 
Debug: Normalized as "C:\Users" 
Debug: Checking pyRevit clone validity "C:\Users" 
Debug: Checking clone validity by directory structure... 
Debug: Normalizing "C:\Users\pyrevitlib" 
Debug: Normalized as "C:\Users\pyrevitlib" 
Debug: Normalizing "C:\Users\pyrevitlib\pyrevit" 
Debug: Normalized as "C:\Users\pyrevitlib\pyrevit" 
Debug: Checking pyRevit path "C:\Users\pyrevitlib\pyrevit" 
Debug: Invalid pyRevit clone. | Path "C:\Users" is not a valid git pyRevit clone. 
Debug: Normalizing "C:\" 
Debug: Normalized as "C:" 
Debug: Checking pyRevit clone validity "C:" 
Debug: Checking clone validity by directory structure... 
Debug: Normalizing "C:pyrevitlib" 
Debug: Path is not local. Skipping normalization "C:pyrevitlib" 
Debug: Normalizing "C:pyrevitlib\pyrevit" 
Debug: Path is not local. Skipping normalization "C:pyrevitlib\pyrevit" 
Debug: Checking pyRevit path "C:pyrevitlib\pyrevit" 
Debug: Invalid pyRevit clone. | Path "C:" is not a valid git pyRevit clone. 
Debug: Searching for valid clones below: C:\Users\DEPLOY~3\AppData\Local\Temp\master 
Debug: Normalizing "C:\Users\DEPLOY~3\AppData\Local\Temp\master" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\master" 
Debug: Checking pyRevit clone validity "C:\Users\deploy-it2\AppData\Local\Temp\master" 
Debug: Checking clone validity by directory structure... 
Debug: Normalizing "C:\Users\deploy-it2\AppData\Local\Temp\master\pyrevitlib" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\master\pyrevitlib" 
Debug: Normalizing "C:\Users\deploy-it2\AppData\Local\Temp\master\pyrevitlib\pyrevit" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\master\pyrevitlib\pyrevit" 
Debug: Checking pyRevit path "C:\Users\deploy-it2\AppData\Local\Temp\master\pyrevitlib\pyrevit" 
Debug: Invalid pyRevit clone. | Path "C:\Users\deploy-it2\AppData\Local\Temp\master" is not a valid git pyRevit clone. 
Debug: Searching for valid clones below: C:\Users\DEPLOY~3\AppData\Local\Temp\master\pyRevit-master 
Debug: Normalizing "C:\Users\DEPLOY~3\AppData\Local\Temp\master\pyRevit-master" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\master\pyRevit-master" 
Debug: Checking pyRevit clone validity "C:\Users\deploy-it2\AppData\Local\Temp\master\pyRevit-master" 
Debug: Checking clone validity by directory structure... 
Debug: Normalizing "C:\Users\deploy-it2\AppData\Local\Temp\master\pyRevit-master\pyrevitlib" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\master\pyRevit-master\pyrevitlib" 
Debug: Normalizing "C:\Users\deploy-it2\AppData\Local\Temp\master\pyRevit-master\pyrevitlib\pyrevit" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\master\pyRevit-master\pyrevitlib\pyrevit" 
Debug: Checking pyRevit path "C:\Users\deploy-it2\AppData\Local\Temp\master\pyRevit-master\pyrevitlib\pyrevit" 
Debug: Checking clone validity by git repo... 
Debug: Valid pyRevit clone "C:\Users\deploy-it2\AppData\Local\Temp\master\pyRevit-master" 
Debug: Valid clone found at: C:\Users\DEPLOY~3\AppData\Local\Temp\master\pyRevit-master 
Debug: Normalizing "C:\Users\DEPLOY~3\AppData\Local\Temp\master\pyRevit-master" 
Debug: Normalized as "C:\Users\deploy-it2\AppData\Local\Temp\master\pyRevit-master" 
Debug: "core" : "["bin", "pyrevitlib", "site-packages", "pyRevitfile"]" 
Debug: "corex" : "["bin", "extensions/pyRevitCore.extension", "extensions/extensions.json", "pyrevitlib", "site-packages", "pyRevitfile"]" 
Debug: "base" : "["bin", "extensions/pyRevitCore.extension", "extensions/pyRevitTags.extension", "extensions/pyRevitTools.extension", "extensions/extensions.json", "pyrevitlib", "site-packages", "pyRevitfile"]" 
Debug: "basepublic" : "["bin", "extensions/pyRevitCore.extension", "extensions/pyRevitTags.extension", "extensions/pyRevitTools.extension", "extensions/pyRevitTutor.extension", "extensions/extensions.json", "pyrevitlib", "site-packages", "pyRevitfile"]" 
Debug: "basex" : "["bin", "extensions", "pyrevitlib", "site-packages", "pyRevitfile"]" 
Debug: "core" : "["bin", "pyrevitlib", "site-packages", "pyRevitfile"]" 
Debug: "corex" : "["bin", "extensions/pyRevitCore.extension", "extensions/extensions.json", "pyrevitlib", "site-packages", "pyRevitfile"]" 
Debug: "base" : "["bin", "extensions/pyRevitCore.extension", "extensions/pyRevitTags.extension", "extensions/pyRevitTools.extension", "extensions/extensions.json", "pyrevitlib", "site-packages", "pyRevitfile"]" 
Debug: "basepublic" : "["bin", "extensions/pyRevitCore.extension", "extensions/pyRevitTags.extension", "extensions/pyRevitTools.extension", "extensions/pyRevitTutor.extension", "extensions/extensions.json", "pyrevitlib", "site-packages", "pyRevitfile"]" 
Debug: "basex" : "["bin", "extensions", "pyrevitlib", "site-packages", "pyRevitfile"]" 
Debug: Found deployment "base" 
Debug: Deploying from "base" 
Error: Illegal characters in path. (System.ArgumentException)
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at pyRevitLabs.PyRevit.PyRevitClones.Deploy(String imagePath, PyRevitDeployment deployment, String destPath)
   at pyRevitLabs.PyRevit.PyRevitClones.Deploy(String fromPath, String deploymentName, String destPath)
   at pyRevitLabs.PyRevit.PyRevitClones.DeployFromImage(String cloneName, String deploymentName, String branchName, String imagePath, String destPath)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)


```

**Comment by eirannejad** [comment]
The problem is that you are using `--image=` option with url of `master.zip` file generated by github. The image file option was designed to allow users to customize their pyRevit install and zip it up into a package. The zip image file structure should be:

```
master.zip/
├── bin
├── extensions
├── pyrevitlib
├── site-packages
└── pyRevitfile
```

whereas the zip file from github is:

```
master.zip/
└── pyRevit-master/
            ├── bin
            ├── extensions
            ├── pyrevitlib
            ├── site-packages
            └── pyRevitfile
``` 

And that throws off the installer. I can potentially fix this but need a safe way to detect if the zip is from github

**Comment by eirannejad** [comment]
Oh. Then this is completely my fault. I wonder what changed... I'll fix and will push a release soon
