### ISSUE TITLE
Copy Viewports (Legends) to Other Sheets Error

### ISSUE THREAD

**Issue by pplutoisaplanet** [eirannejad/pyRevit#1473]
```
ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:viewId cannot be added to the ViewSheet. 
Parameter name: viewId

IronPython Traceback:
Traceback (most recent call last):
 File "D:\Users\Tavares\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Sheets.pulldown\Copy Views.pushbutton\script.py", line 71, in <module>
Exception: viewId cannot be added to the ViewSheet.
Parameter name: viewId


Script Executor Traceback:
Autodesk.Revit.Exceptions.ArgumentException: viewId cannot be added to the ViewSheet.
Parameter name: viewId
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**Comment by yxie-deg** [comment]
was this issue resolved? I'm using the latest pyRevit, this error still came up.
Please let me know. Thank you.

**Comment by jmcouffin** [comment]
@yxie-deg 
The tool works.
I tested all the tools in Revit 2023 on monday
When you say latest version, do you mean 2.12 (which would not work maybe) or one of the latest wip version

**Comment by yxie-deg** [comment]
@jmcouffin 
Hi, thanks for the response. 
I was using v4.8.12.22247, is this the latest version?
I'm also using Revit 2022 which might cause the issue?
Let me know what you think. Thanks.

**Comment by jmcouffin** [comment]
> @jmcouffin Hi, thanks for the response. I was using v4.8.12.22247, is this the latest version? I'm also using Revit 2022 which might cause the issue? Let me know what you think. Thanks.

No it is not. But it is...
It is the latest official release from last year. But in the meantime, a lot of fixes happened. That are available through the WIP installers available under the actions section in this repo.

The next official release integrating all these fixed is coming up very very soon.
