### ISSUE TITLE
Sum Total Tool Not Working Revit 2023

### ISSUE THREAD

**Issue by harecu** [eirannejad/pyRevit#1565]
**Describe the bug**
After following the advice to install the dev branch version of pyRevit for Revit 2023 compatibility, I began testing common tools that our office uses to prep for our transition to R2023. Sum Total tool does not work. Here's the forum post that recommends the dev branch: https://discourse.pyrevitlabs.io/t/error-message-loading-pyrevit-in-2023/948 

Here's the pyRevit version I have installed: 4.8.11.22151

This issue may be caused by an API change between R2022 and R2023. Tool still functions normally in R2022.

**To Reproduce**
1. Install Revit 2023 through the Autodesk Desktop App
2. Install pyRevit 4.8.11.22151 via pyRevit_4.8.11.22151_signed.exe found at Actions > Update Units.py (#1534)
3. Open a new blank project in R2023
4. Draw some detail lines
5. Select detail lines and then click Sum Total button

**Expected behavior**
Sum tool should open selector to allow user to choose which parameter to Sum

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - pyRevit Version: 4.8.11.22151
 - pyRevit Environment:
 ```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.11.22151+0307-wip" | Path: "C:\Users\sdc\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\sdc\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\sdc\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
CGD | Type: Unknown | Repo: "" | Installed: "G:\CGD Revit Standards\06 Custom Plug In\CGD.extension"
==> Default Extension Search Path
C:\Users\sdc\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
G:\CGD Revit Standards\06 Custom Plug In
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.11.19 | Build: 20220503_1030(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Additional context**
```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\sdc\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\Tools.stack\Sum.pushbutton\script.py", line 83, in <module>
AttributeError: 'Autodesk.Revit.DB' object has no attribute 'ParameterType'


Script Executor Traceback:
System.MissingMemberException: 'Autodesk.Revit.DB' object has no attribute 'ParameterType'
 at IronPython.Runtime.Binding.PythonGetMemberBinder.NamespaceTrackerDelegate.Target(CallSite site, Object self, CodeContext context)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
