### ISSUE TITLE
Error after Saved Settings

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#160]
Went into Settings, added a folder to "Extensions" search path, hit save, got the traceback below.

Seems like it might be related to my current setup, in which I only have pyRevit installed in 2015, so 
when it peaks into 2016, it doesn't find it.

Maybe it's a rare edge case, but wouldn't be hard to handle it by checking file before trying to delete.

```
IronPython Traceback:
Traceback (most recent call last): 
File "C:\Users\gtalarico\Dropbox\Shared\dev\repos\pyrevit\pyRevit\extensions\pyRevitCore.extension\pyRevit.tab\pyRevit.panel\Settings.pushbutton\script.py", line 157, in 
File "C:\Users\gtalarico\Dropbox\Shared\dev\repos\pyrevit\pyRevit\extensions\pyRevitCore.extension\pyRevit.tab\pyRevit.panel\Settings.pushbutton\script.py", line 148, in savesettings 
File "C:\Users\gtalarico\Dropbox\Shared\dev\repos\pyrevit\pyRevit\extensions\pyRevitCore.extension\pyRevit.tab\pyRevit.panel\Settings.pushbutton\script.py", line 80, in update_addinfiles 
File "C:\Users\gtalarico\Dropbox\Shared\dev\repos\pyrevit\pyRevit\pyrevitlib\pyrevit\loader\addin\addinfiles.py", line 78, in set_addinfiles_state 
File "C:\Users\gtalarico\Dropbox\Shared\dev\repos\pyrevit\pyRevit\pyrevitlib\pyrevit\loader\addin\addinfiles.py", line 56, in _set_addin_state_for 
WindowsError: [Errno 2] The file could not be found for deletion: C:\Users\gtalarico\AppData\Roaming\Autodesk\Revit\Addins\2016\pyRevit.addin 


Script Executor Traceback:
System.ComponentModel.Win32Exception (0x80004005): WindowsError 
at IronPython.Modules.PythonNT.UnlinkWorker(String path) 
at Microsoft.Scripting.Interpreter.ActionCallInstruction`1.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3) 
at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2) 
at Microsoft.Scripting.Interpreter.FuncCallInstruction`6.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3) 
at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2) 
at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3) 
at IronPython.Compiler.Ast.CallExpression.Invoke2Instruction.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1) 
at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2) 
at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1) 
at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2) 
at IronPython.Runtime.Method.MethodBinding.SelfTarget(CallSite site, CodeContext context, Object target) 
at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1) 
at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3) 
at IronPython.Compiler.PythonCallTargets.OriginalCallTarget3(PythonFunction function, Object arg0, Object arg1, Object arg2) 
at CallSite.Target(Closure , CallSite , Object , Object , RoutedEventArgs ) 
at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2) 
at _Scripting_(Object[] , Object , RoutedEventArgs ) 
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) 
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) 
at System.Windows.Controls.Primitives.ButtonBase.OnClick() 
at System.Windows.Controls.Button.OnClick() 
at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e) 
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) 
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs) 
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) 
at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent) 
at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e) 
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) 
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs) 
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) 
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) 
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args) 
at System.Windows.Input.InputManager.ProcessStagingArea() 
at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input) 
at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport) 
at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel) 
at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled) 
at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) 
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) 
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) 
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) 
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) 
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) 
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) 
at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg) 
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) 
at System.Windows.Window.ShowHelper(Object booleanBox) 
at System.Windows.Window.ShowDialog() 
at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2) 
at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1) 
at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame) 
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1) 
at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx) 
at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope) 
at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(String sourcePath, String syspaths, String cmdName, Boolean forcedDebugMode, Boolean altScriptMode)
```

**Comment by eirannejad** [comment]
Awesome. I'll get it corrected! Thanks!

**Comment by eirannejad** [comment]
Fixed
