### ISSUE TITLE
Create schedule CSV error Revit 2023

### ISSUE THREAD

**Issue by Binbreik** [eirannejad/pyRevit#1646]
I created a CSV file in excel to import into revit. I am trying to create a key schedule that will be used across multiple projects.  I used Key Name as first header and a comma to separate the other headline. The same for the data below, separating key name data and parameter data with a comma. The parameter with exact naming was created in the model under the right category. However, no matter what I try I always get an error.  The error shown below (copied from the error log)

```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Program Files\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\views.stack\Schedules.pulldown\Create Schedule from CSV.pushbutton\script.py", line 344, in <module>
 File "C:\Program Files\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\views.stack\Schedules.pulldown\Create Schedule from CSV.pushbutton\script.py", line 321, in read_csv_typed_data
AttributeError: 'Autodesk.Revit.DB' object has no attribute 'ParameterType'


Script Executor Traceback:
System.MissingMemberException: 'Autodesk.Revit.DB' object has no attribute 'ParameterType'
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

I am attaching the CSV test file as well. Thanks for your help. If you reuire me to provide more info let me know.

[New.csv](https://github.com/eirannejad/pyRevit/files/9854754/New.csv)

**Comment by Binbreik** [comment]
I forgot to mention that I am using Revit 2023. I tested it on Revit 2022 and it works fine

**Comment by eirannejad** [comment]
I believe this is a Revit 2023 compatibility issue that was resolved in the latest version. Would you mind testing that?
