### ISSUE TITLE
Unable to modify document inside doc-changed hook

### ISSUE THREAD

**Issue by baaswietse** [eirannejad/pyRevit#1659]
**Describe the bug**
I created a script that attempts to update a parameter each time an element has been moved (distance to a towercrane). For debugging purposes, all code is inside of the hook script but I will move it into a module afterward.
Revit does not seem to allow modification of the document on a DocumentChanged event. I have read in the RevitAPI docs that I should use the IUpdater interface but I can't seem to find any resources on how to do this in PyRevit.
Any help in the right direction would be great.

**Error**
```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\wdelclef\Desktop\WDE-addins\WDE-addins.extension\hooks\doc-changed.py", line 115, in <module>
 File "C:\Users\wdelclef\Desktop\WDE-addins\WDE-addins.extension\hooks\doc-changed.py", line 76, in updateAfstandTK
Exception: Illegal attempt to modify document. Reason: Raising DocumentChanged event


Script Executor Traceback:
Autodesk.Revit.Exceptions.ModificationForbiddenException: Illegal attempt to modify document. Reason: Raising DocumentChanged event
 at updateAfstandTK$1364(Closure , PythonFunction , Object )
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**Code**
The important part is inside of the updateAfstandTK( ) function.

```
from pyrevit import revit, forms, EXEC_PARAMS, HOST_APP, script
#from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import BooleanOperationsUtils, ElementMulticategoryFilter, FilteredElementCollector, XYZ, \
    Transaction, Options, BooleanOperationsType, BuiltInCategory, BuiltInParameter, ViewDetailLevel

import clr
clr.AddReference("System")
from System.Collections.Generic import List

args = EXEC_PARAMS.event_args

def createUnion(solids):
    union = None
    for solid in solids:
        if union == None:
            union = solid
        else:
            union = BooleanOperationsUtils.ExecuteBooleanOperation(union, solid, BooleanOperationsType.Union)
    return union


def getValidSolids(element):
    solids = []

    opts = Options()
    opts.DetailLevel = ViewDetailLevel.Fine

    elemGeom = element.get_Geometry(opts)

    for geomInstance in elemGeom:
        if geomInstance.ToString() == "Autodesk.Revit.DB.Solid":
            if geomInstance.Faces.Size > 0:
                solids.append(geomInstance)
        elif geomInstance.ToString() == "Autodesk.Revit.DB.GeometryInstance":
            for e in geomInstance.GetInstanceGeometry():
                if e.ToString() == "Autodesk.Revit.DB.Solid":
                    if e.Faces.Size > 0:
                        solids.append(e)
    return solids


def updateAfstandTK(elems):
    # Alle torenkranen selecteren
    towercranes = FilteredElementCollector(revit.doc).OfCategory(BuiltInCategory.OST_SpecialityEquipment). \
        WhereElementIsNotElementType().ToElements()

    # Check of torenkraan met Mark = TK1 bestaat
    TK1 = None
    for towercrane in towercranes:
        mark = towercrane.get_Parameter(BuiltInParameter.ALL_MODEL_MARK).AsString()
        if mark == "TK1":
            TK1 = towercrane

    # exit script als TK1 niet bestaat
    if TK1 is None:
        forms.alert('Geen torenkraan met Mark = TK1', exitscript=True)

    # Positie TK1
    TK1_location = XYZ(TK1.Location.Point.X, TK1.Location.Point.Y, 0)  # Coordinaten zijn volgens internal origin!

    with Transaction(revit.doc, "Towercrane updater"):
        for element in elems:
            # Solids uit element halen + center van deze solids bepalen
            solids = getValidSolids(element)
            solidUnion = createUnion(solids)
            centeroid = solidUnion.ComputeCentroid()  # Coordinaten zijn volgens internal origin!

            centeroid_location = XYZ(centeroid.X, centeroid.Y, 0)  # zelfde als centeroid maar met Z=0

            # Afstand tussen TK en element
            dist = TK1_location.DistanceTo(centeroid_location)
            # print(UnitUtils.ConvertFromInternalUnits(dist, UnitTypeId.Centimeters)) #Interne eenheden zijn in Feet

            # Parameter overschrijven
            element.LookupParameter('WDE_Afstand_TK').Set(dist)


log = {
        "cancellable?": str(args.Cancellable),
        "doc": str(revit.doc),
        "added": str(args.GetAddedElementIds().Count),
        "deleted": str(args.GetDeletedElementIds().Count),
        "modified": str(args.GetModifiedElementIds().Count),
        "txn_names": str(list(args.GetTransactionNames())),
        "operation": str(args.Operation),
        "elements": str(args.GetModifiedElementIds()),
    }
print(log)

allowed_transactions = ['Move', 'Nudge Left', 'Nudge Right', 'Nudge Down', 'Nudge Up', 'Copy', ]
transactions = list(args.GetTransactionNames())

allowed_categories = [BuiltInCategory.OST_StructuralFraming, BuiltInCategory.OST_Walls,
                      BuiltInCategory.OST_StructuralColumns, BuiltInCategory.OST_GenericModel,
                      BuiltInCategory.OST_Floors]
filterList = List[BuiltInCategory](allowed_categories)
filterElement = ElementMulticategoryFilter(List[BuiltInCategory](allowed_categories))

elementIds = []
elements = []

if args.GetAddedElementIds().Count > 0: # Wanneer element werd toegevoegd
    addedElementIds = args.GetAddedElementIds(filterElement)
    elementIds.extend(addedElementIds)
if any(item in transactions for item in allowed_transactions):
    modifiedElementIds = args.GetModifiedElementIds(filterElement)
    elementIds.extend(modifiedElementIds)
if len(elementIds) > 0:
    print(elementIds)
    for elementId in elementIds:
        el = revit.doc.GetElement(elementId)
        elements.append(el)
    print(elements)
    updateAfstandTK(elements)
```

**Comment by baaswietse** [comment]
Thank you for the example, it works!
In my case, I need to detect whenever an element moves, so I need the _DB.Element.GetChangeTypeAny()_, have you ever used this? I am worried about creating an infinite loop, when the updater changes a parameter, it could trigger itself again.

**Comment by dvdgnz** [comment]
I have used that before, I don't remember if you need guards in place or Revit handles that. You'll have to try and see if a loop actually happens. Worst case save the ElementIds in an Set as you modify them and when the updater finds it in that set does nothing and removes it.

**Comment by eirannejad** [comment]
@dvdgnz Thanks for the response and example
