### ISSUE TITLE
Spy error related to 'GetSpecTypeId' in Revit 2023

### ISSUE THREAD

**Issue by two9seven** [eirannejad/pyRevit#1718]
Running the spy tool in Revit 2023,  to show project parameters, I get an error referencing 'GetSpecTypeId'. I found a reference to an API change that affects it here:
https://thebuildingcoder.typepad.com/files/revit_platform_api_changes_and_additions_2022.pdf

Here is the error:

Project Parameters

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\donovan.TACOMA\AppData\Roaming\pyRevit-Master\extensions\pyRevitCore.extension\pyRevit.tab\pyRevit.panel\tools.stack\Spy.pulldown\List Elements.pushbutton\script.py", line 110, in <module>
 File "C:\Users\donovan.TACOMA\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\revit\db\query.py", line 463, in get_project_parameters
 File "C:\Users\donovan.TACOMA\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\revit\db\__init__.py", line 179, in __init__
AttributeError: 'InternalDefinition' object has no attribute 'GetSpecTypeId'

Script Executor Traceback:
System.MissingMemberException: 'InternalDefinition' object has no attribute 'GetSpecTypeId'
 at IronPython.Runtime.Binding.PythonGetMemberBinder.FastErrorGet`1.GetError(CallSite site, TSelfType target, CodeContext context)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run5[T0,T1,T2,T3,T4,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`7.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run7[T0,T1,T2,T3,T4,T5,T6,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
 at IronPython.Runtime.Types.LateBoundInitBinder.FastInitSite`3.CallTarget(CallSite site, CodeContext context, Object inst, T0 arg0, T1 arg1, T2 arg2)
 at IronPython.Runtime.Types.PythonType.FastTypeSite`3.CallTarget(CallSite site, CodeContext context, Object type, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`6.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by jmcouffin** [comment]
Thanks @two9seven 
already fixed by https://github.com/eirannejad/pyRevit/pull/1607
You can get the latest version including this revision installing from on of the installers you can download here https://github.com/eirannejad/pyRevit/actions/runs/4056770773 at the bottom of the page
