### ISSUE TITLE
Can not find cpython engines

### ISSUE THREAD

**Issue by dankinnett** [eirannejad/pyRevit#1779]
Hi, after installing the latest version pyrevit I got this error message "Can not find cpython engines".  Any idea what I did wrong?

![image](https://user-images.githubusercontent.com/46876008/229181076-4ff23648-ddc9-4caa-90d4-20e58bed3534.png)

**Comment by jmcouffin** [comment]
Can you run `pyrevit env` command and post the report
Also, check out this previous issue as a possible fix https://github.com/eirannejad/pyRevit/issues/605

**Comment by dankinnett** [comment]
Hi jmcouffin, thanks for your assistance.  I checked post #605 and did not have folders 368 or 372 after install.  Any idea why / where I can get download them?  They didn't appear to be in the source files for the latest release either.  I also ran pyrevit env in command and got these result:

**Comment by jmcouffin** [comment]
regarding the folder you should have these, or most of these here %AppData%\Roaming\pyRevit-Master\bin\engines\
![image](https://user-images.githubusercontent.com/7872003/229856263-573a4c26-f33a-4b62-a8e8-49d888068406.png)
If you don't have one of the CPY folder, then that is why it cannot find cpython engine (> uninstall and install again)
If you have it, I suggest you try to attach you pyrevit version to Revit with a different engine with the command line;
`pyrevit attach master 2711 --installed --allusers`

Alternatively, you could try to uninstall and use one of the WIP installer you can find under the actions tab in github in the artifacts of one of the actions

**Comment by dankinnett** [comment]
Hi jmcouffin,

I have both of the CPY folders and they both have content in them (see attached).  I am, however, missing the IMPY340PR folder.  Could that be the issue?  I've already tried uninstalling and reinstalling using both exe files.  I'm not savvy enough to understand your alternative solution "you could try to uninstall and use one of the WIP installer you can find under the actions tab in github in the artifacts of one of the actions."  Can you clarify?

![image](https://user-images.githubusercontent.com/46876008/229878092-b21d9bde-91f5-4fd8-a9e3-554b6ee66713.png)
![image](https://user-images.githubusercontent.com/46876008/229878221-39dadedd-b483-4307-9ba1-a107b8196342.png)
![image](https://user-images.githubusercontent.com/46876008/229878317-32092f31-07c3-4913-8f02-ce0ee655811d.png)

Thanks again!

**Comment by jmcouffin** [comment]
The missing folder isn't the issue.
Sure, the files located in the actiond/workflow section of this repo. Those are the latest version / work in progress between releases
https://github.com/eirannejad/pyRevit/suites/11989975393/artifacts/629413860

**Comment by dankinnett** [comment]
Hey jmcouffin, I tried the pyRevit_4.8.13.23093_signed and pyRevit_4.8.13.23093_admin_signed installers in that folder.  Still having the same issue (see attached).

**Comment by jmcouffin** [comment]
Have you tried the command line ⬆️ ?

**Comment by dankinnett** [comment]
I tried the both of the CLI installers.  I don't get an error message regarding the cpython engines on start up any more, but I don't see any pyrevit tools when I open Revit... even though I see the application in my installed apps (see attached).

![image](https://user-images.githubusercontent.com/46876008/229905845-ae3fa3b4-5e3c-46ea-93b8-55617bb5e15b.png)

Thanks

**Comment by jmcouffin** [comment]
ok,
let me clarify.
The command line I mention is something similar to the `pyrevit env` command you ran. 
The result of the pyrevit env command now tells me you have only pyRevit CLI installed (CLI stands for Command Line Interface) > no pyRevit addin installed, just the command line version of pyRevit, so it is normal to not have anything showing in pyRevit.
for reference: 
https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725
https://pyrevitlabs.notion.site/pyRevit-CLI-c50de95259114db795db5bd3f19f8e2a
https://pyrevitlabs.notion.site/pyRevit-For-Teams-ddc6c312d6f6488691eed2ec7704fd97
https://pyrevitlabs.notion.site/Manage-pyRevit-clones-e9f789f9431346b482021f2a87a6dabf

Two options from there. You go grab one of the installers, either from the release section or from the actions section in the repo
OR
you install pyRevit from the command line running this command for example
`pyrevit clone master`
then 
`pyrevit attach master 2711 --installed --allusers`

**Comment by dankinnett** [comment]
Hi jmcouffin,

thanks for the clarification.  My understanding is obviously quite superficial.  I've tried all of the installers in the release section and the actions section.  Same issue persists.  I tried using the command line to install as well... but I may be getting a bit our of my depth.  This is what I get when I try the second alternative that you proposed using the command prompt:

U:\>pyrevit clone master
Error: Destination path already exists "C:\Users\daniel kinnett\AppData\Roaming\pyRevit\pyRevit\master"
Run with "--debug" option to see debug messages

U:\>pyrevit attach master 2711 --installed --allusers

U:\>pyrevit clone master --debug
clone = True
<clone_name> = master
Debug: Checking for all: wiki
Debug: Missing: wiki
Debug: Checking for all: blog
Debug: Missing: blog
Debug: Checking for all: docs
Debug: Missing: docs
Debug: Checking for all: source
Debug: Missing: source
Debug: Checking for all: youtube
Debug: Missing: youtube
Debug: Checking for all: support
Debug: Missing: support
Debug: Checking for all: env
Debug: Missing: env
Debug: Checking for all: update
Debug: Missing: update
Debug: Checking for all: clone
Debug: Repo source determined as "https://github.com/eirannejad/pyRevit.git:master"
Debug: Destination path determined as "C:\Users\daniel kinnett\AppData\Roaming\pyRevit\pyRevit"
Debug: Destination path already exists C:\Users\daniel kinnett\AppData\Roaming\pyRevit\pyRevit
Debug: Using subpath C:\Users\daniel kinnett\AppData\Roaming\pyRevit\pyRevit\master
Error: Destination path already exists "C:\Users\daniel kinnett\AppData\Roaming\pyRevit\pyRevit\master" (pyRevitLabs.Common.PyRevitException)
   at pyRevitLabs.PyRevit.PyRevitClones.DeployFromRepo(String cloneName, String deploymentName, String branchName, String repoUrl, String destPath, GitInstallerCredentials credentials)
   at pyRevitCLI.PyRevitCLICloneCmds.CreateClone(String cloneName, String deployName, String branchName, String repoUrl, String imagePath, String destPath, GitInstallerCredentials credentials)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)

U:\>

**Comment by jmcouffin** [comment]
this: 

> Error: Destination path already exists "C:\Users\daniel kinnett\AppData\Roaming\pyRevit\pyRevit\master"

tells you you already have an installation or a clone of pyRevit available there. 

1. Remove the folder C:\Users\daniel kinnett\AppData\Roaming\pyRevit
2. and rerun the 2 command lines mentioned earlier

**Comment by dankinnett** [comment]
Hey jmcouffin,

After deleting the pyRevit folder and running the 2 commands that you mentioned earlier, these are the results that I get:

Microsoft Windows [Version 10.0.22621.1413]
(c) Microsoft Corporation. All rights reserved.

U:\>revit clone master
'revit' is not recognized as an internal or external command,
operable program or batch file.

U:\>pyrevit attach master 2711 --installed --allusers
'pyrevit' is not recognized as an internal or external command,
operable program or batch file.

U:\>

**Comment by dankinnett** [comment]
Hi jmcouffin,

**Comment by dankinnett** [comment]
hey jmcouffin,

After deleting the folder I ran reran the two command lines mentioned above.  Unfortunately, still getting the same error that the system can not find cpython engines.

**Comment by dankinnett** [comment]
Hi jmcouffin,

Still having issues.  I've tried all of the recommendations above?  Any other ideas?  Thanks.

**Comment by brown313** [comment]
We have come across this same issue, even with the very latest version 4.8.13. We have found it is caused by having Windows FIPS mode enabled, which is a requirement for some of our users. If we disable FIPS, it works without issue.

**Comment by jmcouffin** [comment]
> Still having issues. I've tried all of the recommendations above? Any other ideas? Thanks.

Can you try @brown313 recommandation @dankinnett ?

**Comment by Haunfelder** [comment]
@brown313 Can you expand on how you disabled FIPs mode? What do you think is the cause of this mode blocking pyrevit from finding the cpython engines?

**Comment by brown313** [comment]
In regedit, set HKLM\System\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy\Enabled to 0
It's likely caused by a cryptographic module/algorithm being used that isn't FIP 140 compliant.
[https://learn.microsoft.com/en-us/windows/security/security-foundations/certification/fips-140-validation](url) may be helpful in further understanding

**Comment by dankinnett** [comment]
I figured out the issue for our office.  When we installed as admin, the
intaller was putting the python files in a location that Revit couldn't
access.  Re-installing without running as an administrator solved the issue
for us.

Thanks,

Dan
