### ISSUE TITLE
REQUEST: Centre of gravity finder

### ISSUE THREAD

**Issue by dr3141** [eirannejad/pyRevit#1830]
**Is your feature request related to a problem? Please describe.**
Working in precast industry finding a centre of gravity for an assembly is crucial to our day to day work. This can be done with the use of dynamo but it's a bit cumbersome. There used to be a great Revit add-in specifically for this, but  the devs stopped supporting it after Revit 2020.

**Describe the solution you'd like**
A one click solution within Revit for finding centre of gravity, anything similar to what this add-in does on older versions of Revit:
https://apps.autodesk.com/RVT/en/Detail/Index?id=2883284966960053552&appLang=en&os=Win64
The add-in locates the centroid of selected assembly and places three short lines XYZ in the model.

**Describe alternatives you've considered**
Dynamo scripts, alternative add-ins, exporting assemblies to CAD and using AUTOCAD, all work to some extent but not very user friendly, consistent or easy to use.

**Comment by thumDer** [comment]
This could be quite easy to implement, `Solid` class has a `GetCentroid()` or similar method to get the coordinates of the complete element geometries centroid, just keep in mind it is the center of gravity only if the element has one single material only. If that is what you meant it is possible.

**Comment by dr3141** [comment]
> This could be quite easy to implement, `Solid` class has a `GetCentroid()` or similar method to get the coordinates of the complete element geometries centroid, just keep in mind it is the center of gravity only if the element has one single material only. If that is what you meant it is possible.

That's exactly what I meant, coordinates of the centroid for a single material element.

**Comment by jmcouffin** [comment]
resolved by #1857

**Comment by dr3141** [comment]
Thank you both! It works great with families and generic models! 

Is there any chance the three lines that indicate the centre o gravity use a custom line style? For easy distinction from other lines in the model? For example 'CoG line' or something similar?

On a side note, for any potential users, it does not work when selecting an assembly (it produces an error - see below), so you need to make sure to filter assemblies out of your selection. Apart from that, it's great!

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\dr\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\Tools.stack\Analyse.pulldown\Get Centroid.pushbutton\script.py", line 59, in <module>
 File "C:\Users\dr\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\revit\db\query.py", line 1579, in get_geometry
TypeError: iteration over non-sequence of type NoneType


Script Executor Traceback:
IronPython.Runtime.Exceptions.TypeErrorException: iteration over non-sequence of type NoneType
 at IronPython.Runtime.Operations.PythonOps.ThrowTypeErrorForBadIteration(CodeContext context, Object enumerable)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
 at CallSite.Target(Closure , CallSite , Object )
 at get_geometry$1365(Closure , PythonFunction , Object , Object , Object )
 at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by thumDer** [comment]
That seems to be an error in pyrevits query module, assemblies don't have direct geometries, only the contained elements. Will do a quick fix.
We could add a line style selector to the shift+click option, where you can set a specific lifestyle as the primary option, and keep the default one as a fallback. What do you think @dr3141 ?

**Comment by thumDer** [comment]
#1870 to solve the assembly issue

**Comment by dr3141** [comment]
Shitf+click option sounds fantastic, thank you!

**Comment by thumDer** [comment]
#1872 for config mode
