### ISSUE TITLE
Error running Create Workset for Linked Element when element is already on workset

### ISSUE THREAD

**Issue by gnomesoup** [eirannejad/pyRevit#1938]
**Describe the bug**
I receive the following error when running the Create Workset for Linked Element command.

```
ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:The given workset name is already in use. 
Parameter name: name

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\michael_p\AppData\Roaming\pyRevit\pyRevit\master\extensions\pyRevitTools.extension\pyRevit.tab\Project.panel\ptools.stack\Links.pulldown\Create Workset For Linked Element.pushbutton\script.py", line 25, in <module>
Exception: The given workset name is already in use.
Parameter name: name

Script Executor Traceback:
Autodesk.Revit.Exceptions.ArgumentException: The given workset name is already in use.
Parameter name: name
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**To Reproduce**
1. Select a linked Revit model that is already placed on a worket with the same name as the link
2. Click on 'Create Workset for Linked Element'
3. See error

**Expected behavior**
The pyRevit output window should report that the element is already placed on a properly named workset

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version: 20
 - pyRevit Environment: 
```
==> Registered Clones (full git repos)
develop | Branch: "develop" | Version: "4.8.13:9363233" | Path: "C:\Users\michael_p\AppData\Roaming\pyrevit\pyrevit\develop"
master | Branch: "master" | Version: "4.8.13.23182+2215:6aa2c49" | Path: "C:\Users\michael_p\AppData\Roaming\pyRevit\pyRevit\master"
==> Registered Clones (deployed from archive/image)
==> Attachments
master | Product: "Autodesk Revit 2024" | Engine: IPY2710 (2710) | Path: "C:\Users\michael_p\AppData\Roaming\pyRevit\pyRevit\master" | AllUsers
master | Product: "Autodesk Revit 2023" | Engine: IPY2710 (2710) | Path: "C:\Users\michael_p\AppData\Roaming\pyRevit\pyRevit\master" | AllUsers
master | Product: "Autodesk Revit 2022" | Engine: IPY2710 (2710) | Path: "C:\Users\michael_p\AppData\Roaming\pyRevit\pyRevit\master" | AllUsers
master | Product: "Autodesk Revit 2021" | Engine: IPY2710 (2710) | Path: "C:\Users\michael_p\AppData\Roaming\pyRevit\pyRevit\master" | AllUsers
master | Product: "Autodesk Revit 2020" | Engine: IPY2710 (2710) | Path: "C:\Users\michael_p\AppData\Roaming\pyRevit\pyRevit\master" | AllUsers
master | Product: "2019.2.6" | Engine: IPY2710 (2710) | Path: "C:\Users\michael_p\AppData\Roaming\pyRevit\pyRevit\master" | AllUsers
==> Installed Extensions
flamingo | Type: Unknown | Repo: "git@github.com:gnomesoup/flamingo.lib" | Installed: "C:\Users\michael_p\flamingo\flamingo.lib"
flamingo | Type: Unknown | Repo: "git@github.com:gnomesoup/flamingo.lib" | Installed: "C:\Users\michael_p\pyKSP\flamingo.lib"
Flamingo | Type: Unknown | Repo: "" | Installed: "C:\Users\michael_p\flamingo\Flamingo.extension"
KSP | Type: Unknown | Repo: "" | Installed: "C:\Users\michael_p\pyKSP\KSP.extension"
KSP | Type: Unknown | Repo: "" | Installed: "C:\Users\michael_p\pyKSP\KSP.lib"
==> Default Extension Search Path
C:\Users\michael_p\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\michael_p\flamingo
C:\Users\michael_p\pyKSP
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2024 | Version: 24.1.10.25 | Build: 20230830_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
Autodesk Revit 2023 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.6 | Version: 19.2.60.3 | Build: 20220224_1700(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Additional context**
None

**Comment by jmcouffin** [comment]
Fixed by https://github.com/eirannejad/pyRevit/pull/1943 (CI/CD takes 10/15mins before producing installers)

To try it out use WIP installers under the action tab of this repo
Instructions at the bottom of this page
