### ISSUE TITLE
Export Family Config failed while exporting

### ISSUE THREAD

**Issue by harecu** [eirannejad/pyRevit#2009]
**Describe the bug**
Export Family Config failed while exporting.

**To Reproduce**
1. While editing a Revit annotation family
2. Click on pyRevit tab, Family dropdown, Export Family Config
3. A filepath finder pops up, type in a filename and click save
4. Select parameters to copy, click Select.
5. Question pops up asking "Do you want to export family types as well?" Select No.
6. Question pops up asking "Do you want to include the current parameter values as default?" Select Yes. (selecting No also leads to error)
7. Error occurs.

**Expected behavior**
Expected config .yaml file to be created with selected parameters.

**Screenshots**
![image](https://github.com/eirannejad/pyRevit/assets/6211847/7199def9-1107-433f-bab2-40b7d35c19f9)
![image](https://github.com/eirannejad/pyRevit/assets/6211847/7bbcc5bb-6b9d-425d-9aef-d2c44e8e1f4f)
![image](https://github.com/eirannejad/pyRevit/assets/6211847/956712b6-cd79-4f50-8878-dd05572a12e9)

**Desktop (please complete the following information):**
 - See Device specifications pasted from PC properties:
 Device name	DESKTOP-H68U8CI
Full device name	DESKTOP-H68U8CI.CGD.int
Processor	11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz   2.61 GHz
Installed RAM	32.0 GB (31.2 GB usable)
Device ID	F7DE3BE4-C87C-406C-914F-0416FA0E8667
Product ID	00355-62660-50355-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

 - pyRevit Version 4.8.12.22247+0031:277:2023.1.20
 - pyRevit Environment: 

```C:\Users\sdc>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\sdc\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\sdc\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\sdc\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
CGD | Type: Unknown | Repo: "" | Installed: "G:\CGD Revit Standards\06 Custom Plug In\CGD.extension"
==> Default Extension Search Path
C:\Users\sdc\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
G:\CGD Revit Standards\06 Custom Plug In
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.1.20.70 | Build: 20230510_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.40.58 | Build: 20230505_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Additional context**
See pyrevit error below:
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\sdc\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Project.panel\ptools.stack\Family.pulldown\Export Family Config.pushbutton\script.py", line 334, in <module>
 File "C:\Users\sdc\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Project.panel\ptools.stack\Family.pulldown\Export Family Config.pushbutton\script.py", line 208, in read_configs
AttributeError: 'InternalDefinition' object has no attribute 'ParameterType'

Script Executor Traceback:
System.MissingMemberException: 'InternalDefinition' object has no attribute 'ParameterType'
 at IronPython.Runtime.Binding.PythonGetMemberBinder.FastErrorGet`1.GetError(CallSite site, TSelfType target, CodeContext context)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at IronPython.Compiler.PythonCallTargets.OriginalCallTarget3(PythonFunction function, Object arg0, Object arg1, Object arg2)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`6.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run6[T0,T1,T2,T3,T4,T5,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`6.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by harecu** [comment]
Fixed in version 4.8.13 release #1793
