### ISSUE TITLE
pyRevit 4.8.14 ControlEz: Could not load type

### ISSUE THREAD

**Issue by dosymep** [eirannejad/pyRevit#2012]
# 🐞 Describe the bug

```
[Window Title]
PyRevitLoader - Error Loading pyRevit

[Main Instruction]
IronPython Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\pyRevit\bin\engines\pyRevitLoader.py", line 33, in <module>
  File "D:\Projects\Python\pyRevit\pyrevitlib\pyrevit\loader\sessionmgr.py", line 272, in load_session
  File "D:\Projects\Python\pyRevit\pyrevitlib\pyrevit\loader\sessionmgr.py", line 66, in _setup_output
SystemError: Could not load type 'ControlzEx.Standard.WINDOWPOS' from assembly 'ControlzEx, Version=6.0.0.0, Culture=neutral, PublicKeyToken=69f1c32f803d307e'.


Script Executor Traceback:
System.TypeLoadException: Could not load type 'ControlzEx.Standard.WINDOWPOS' from assembly 'ControlzEx, Version=6.0.0.0, Culture=neutral, PublicKeyToken=69f1c32f803d307e'.
   at Microsoft.Scripting.Interpreter.NewInstruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
   at PyRevitLoader.ScriptExecutor.ExecuteScript(String sourcePath, IEnumerable`1 sysPaths, String logFilePath, IDictionary`2 variables)
```

![image](https://github.com/eirannejad/pyRevit/assets/5417225/79161f28-e164-410b-ad35-1daf3fa6f3ce)

**Comment by dosymep** [comment]
I think MahApps.Metro 1.6.0 does not support ControlEZ 6.0.0

**Comment by jmcouffin** [comment]
How do you suggest we fix it? @dosymep

**Comment by dosymep** [comment]
I updated pyRevit and then catch the error.

```
[Window Title]
PyRevitLoader - Error Loading pyRevit

[Main Instruction]
IronPython Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\pyRevit\bin\engines\pyRevitLoader.py", line 33, in <module>
  File "D:\Projects\Python\pyRevit\pyrevitlib\pyrevit\loader\sessionmgr.py", line 272, in load_session
  File "D:\Projects\Python\pyRevit\pyrevitlib\pyrevit\loader\sessionmgr.py", line 66, in _setup_output
SystemError: The type initializer for 'pyRevitLabs.MahAppsMetro.Controls.MetroWindow' threw an exception.


Script Executor Traceback:
System.TypeInitializationException: The type initializer for 'pyRevitLabs.MahAppsMetro.Controls.MetroWindow' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Xaml.Behaviors, Version=1.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Не удается найти указанный файл.
   at pyRevitLabs.MahAppsMetro.Controls.MetroWindow..cctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Scripting.Interpreter.NewInstruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
   at PyRevitLoader.ScriptExecutor.ExecuteScript(String sourcePath, IEnumerable`1 sysPaths, String logFilePath, IDictionary`2 variables)
```

**Comment by dosymep** [comment]
> How do you suggest we fix it? @dosymep

Needs update MahApps.Metro with their dependencies, but it will broke everything

**Comment by jmcouffin** [comment]
> I updated pyRevit and then catch the error.

Do you mean you updated from my latest commit in the develop branch or you installed the latest artifacts in the latest workflow run in the actions? @dosymep

**Comment by jmcouffin** [comment]
> > How do you suggest we fix it? @dosymep
> 
> Needs update MahApps.Metro with their dependencies, but it will broke everything

or create a separate solution with a difference named namespace and change the namespaces in all the C# code of the MahApps.metro project and recompile.. .

**Comment by dosymep** [comment]
> Do you mean you updated from my latest commit in the develop branch or you installed the latest artifacts in the latest workflow run in the actions?

updated from latest commit in develop branch

**Comment by dosymep** [comment]
> or create a separate solution with a difference named namespace and change the namespaces in all the C# code of the MahApps.metro project and recompile.. .

this won't work, because MahApps was [updated](https://mahapps.com/docs/guides/migration-to-v2.0)

**Comment by jmcouffin** [comment]
> > Do you mean you updated from my latest commit in the develop branch or you installed the latest artifacts in the latest workflow run in the actions?
> 
> updated from latest commit in develop branch

From this one?
https://github.com/eirannejad/pyRevit/commit/c6454490f3109da5bf2e48e32eb32dff2f61cd5d
That should work...

**Comment by dosymep** [comment]
@jmcouffin, yep

```
PS D:\Projects\Python\pyRevit\bin> pyrevit clones
==> Registered Clones (full git repos)
develop | Branch: "develop" | Version: "4.8.14:c645449" | Path: "D:\Projects\Python\pyRevit"
==> Registered Clones (deployed from archive/image)
```

![image](https://github.com/eirannejad/pyRevit/assets/5417225/80d9eff6-9887-456a-9103-c36dedb5e71d)

**Comment by jmcouffin** [comment]
> @jmcouffin, yep
> 
> ```
> PS D:\Projects\Python\pyRevit\bin> pyrevit clones
> ==> Registered Clones (full git repos)
> develop | Branch: "develop" | Version: "4.8.14:c645449" | Path: "D:\Projects\Python\pyRevit"
> ==> Registered Clones (deployed from archive/image)
> ```
> 
> ![image](https://user-images.githubusercontent.com/5417225/285407045-80d9eff6-9887-456a-9103-c36dedb5e71d.png)

ok, I will just rollback the changes for now
