### ISSUE TITLE
Need Help with this error Please

### ISSUE THREAD

**Issue by virtdesign17** [eirannejad/pyRevit#2017]
Hi im just tyring to run the list walls in project button on PyChizler, but im recieving this error message.

ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:A valid point must not be father then 10 miles (approx. 16 km) from the origin. 
Parameter name: position

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Jad Newman\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Template.panel\template2.stack\List Walls.pushbutton\script.py", line 123, in <module>
 File "C:\Users\Jad Newman\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Template.panel\template2.stack\List Walls.pushbutton\script.py", line 24, in label_placer
Exception: A valid point must not be father then 10 miles (approx. 16 km) from the origin.
Parameter name: position

Script Executor Traceback:
Autodesk.Revit.Exceptions.ArgumentException: A valid point must not be father then 10 miles (approx. 16 km) from the origin.
Parameter name: position
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

Are you able to help me with this please.

Regards
Jad

**Comment by jmcouffin** [comment]
@virtdesign17 the issue is not related to pyRevit and its code base but to this repo https://github.com/dnenov/pyChilizer
pyChilizer being a separate tool / extension developed by Archilizer people.
File in an issue there, please.
And give a file to reproduce the issue, as this issue seems to be file specific.
