### ISSUE TITLE
Error When Reloading (Stream Not Writable)

### ISSUE THREAD

**Issue by SeiyaMoriArup** [eirannejad/pyRevit#2089]
**🙏 Please use the search in the issue section before filing a new issue**

---

# 🐞 Describe the bug

After clicking the Reload button in the pyRevit ribbon and proceeding with the reload, the following error occurs and the reload fails.

**This error happens most of the time. But sometimes the Reload does work.**

# ♻️ To Reproduce
1. Open a Revit project as normal.
2. Go to the pyRevit ribbon and click on Reload.
3. Click Yes to proceed with reload.
4. Error occurs.

# ⏲️ Expected behavior
pyRevit should reload without any warning/error messages (normally takes 10-20 seconds).

# 🖼 Screenshots of the issue

![image](https://github.com/eirannejad/pyRevit/assets/108006025/8456e50a-d83e-4969-9eaa-cd21d8ef7bbe)
```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\ProgramData\pyRevit\arup-clone-base-admin\extensions\pyRevitCore.extension\pyRevit.tab\pyRevit.panel\tools.stack\Reload.pushbutton\script.py", line 32, in <module>
 File "C:\ProgramData\pyRevit\arup-clone-base-admin\pyrevitlib\pyrevit\loader\sessionmgr.py", line 323, in reload_pyrevit
 File "C:\ProgramData\pyRevit\arup-clone-base-admin\pyrevitlib\pyrevit\loader\sessionmgr.py", line 281, in load_session
 File "C:\ProgramData\pyRevit\arup-clone-base-admin\pyrevitlib\pyrevit\loader\sessionmgr.py", line 105, in _perform_onsessionloadstart_ops
 File "C:\ProgramData\pyRevit\arup-clone-base-admin\pyrevitlib\pyrevit\loader\sessionmgr.py", line 57, in _clear_running_engines
StandardError: Exception has been thrown by the target of an invocation.

Script Executor Traceback:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Stream was not writable.
 at System.IO.StreamWriter..ctor(Stream stream, Encoding encoding, Int32 bufferSize, Boolean leaveOpen)
 at System.IO.StreamWriter..ctor(Stream stream, Encoding encoding)
 at Microsoft.Scripting.Hosting.ScriptIO.SetOutput(Stream stream, Encoding encoding)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.CleanupStreams()
 --- End of inner exception stack trace ---
 at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
 at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
 at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
 at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

# 🖥️ Hardware and Software Setup (please complete the following information):
 - OS: Microsoft Windows [Version 10.0.19045.3930]
 - pyRevit Version [e.g. 22]
 - ![image](https://github.com/eirannejad/pyRevit/assets/108006025/0e17a15d-9989-42ff-8d0b-13d2f961f9a8)

 - pyRevit Environment: 
```
C:\Users\seiya.mori>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
arup-clone-base-admin | Deploy: "base" | Branch: "master" | Version: "4.8.14.24016+1909" | Path: "C:\ProgramData\pyRevit\arup-clone-base-admin"
==> Attachments
arup-clone-base-admin | Product: "Autodesk Revit 2023" | Engine: IPY2710 (2710) | Path: "C:\ProgramData\pyRevit\arup-clone-base-admin" | AllUsers
arup-clone-base-admin | Product: "Autodesk Revit 2022" | Engine: IPY2710 (2710) | Path: "C:\ProgramData\pyRevit\arup-clone-base-admin" | AllUsers
arup-clone-base-admin | Product: "Autodesk Revit 2021" | Engine: IPY2710 (2710) | Path: "C:\ProgramData\pyRevit\arup-clone-base-admin" | AllUsers
arup-clone-base-admin | Product: "2020.2.0" | Engine: IPY2710 (2710) | Path: "C:\ProgramData\pyRevit\arup-clone-base-admin" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\seiya.mori\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
\\global\systems\Software\PyRevit Config\extensions.json
==> Installed Revits
Autodesk Revit 2023 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.0 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages```

# Additional context
Add any other context about the problem here.

**Comment by SeiyaMoriArup** [comment]
Update:

- I followed the suggestion of another pyRevit user to see if any other Revit Add-ins were somehow causing this issue.
- I had recently installed the Pollination-Revit plugin.
- I uninstalled the Pollination-Revit plugin and so far the issue has not occurred.
- I suspect the Pollination-Revit plugin was also 'streaming' some data and not allowing the pyRevit Reload script to do so.
- Will close this issue.
