### ISSUE TITLE
Wipe button for unused view tags

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#247]
We have people that work in projects and cut sections everywhere and the issue being that they just leave them. Is there a way for the wipe button to work by getting rid of detail views on sheets only that are unused? (Unused meaning they don’t have a placement on another sheet or detail)

**Comment by ArcDoxDev** [comment]
This can be done with Dynamo easily enough so it can also be done with python.
I used to use ReviBOX for all my modelling when in Revit 2014, but the app has not been revised since then. It was great for modelling e.g. you section box into a location push/pull the face of the section box were you want to work, click on the ReviBOX button and you have a new section that focuses only in the area you want and the best part, when you go 2 or more views away the view deletes automatically.
I would buy an app that had this functionality in second.
https://apps.autodesk.com/RVT/en/Detail/Index?id=3578570540554499675&appLang=en&os=Win32_64

**Comment by eirannejad** [comment]
@ArcDoxDev Very interesting...

**Comment by joseph-kirkpatrick** [comment]
It does look pretty interesting but I have 0 projects in 2014, most of mine are 2016-2018

**Comment by eirannejad** [comment]
Resolved for v4.5rc

**Comment by eirannejad** [comment]
v4.5rc is available now:
http://eirannejad.github.io/pyRevit/pyrevit/update/2017/12/02/45rc.html

**Comment by joseph-kirkpatrick** [comment]
I followed the how to update trying first the update button in revit, which
didn't seem like it wanted to work. Then i tried doing the bat file in the
pyrevit folder name which said in the C:// prompt that it was up to date.
However when i click pyrevit>about in revit it says its still version 4.4?

I went and uninstalled, tried to reinstall and hit the update button, now
its saying it cant find command with unique name
pyRevitCorepyRevitpyRevittoolsReload.

**Comment by eirannejad** [comment]
v4.5 rc is release candidate and is not a final version. You need to use the installer I linked in the blog post.

**Comment by joseph-kirkpatrick** [comment]
i used the installer, but do i need to uninstall the regular pyRevit?

[image: Inline image 1]

**Comment by joseph-kirkpatrick** [comment]
I checked programs and features, it shows 4.5 installed however nothing is
in revit?

**Comment by joseph-kirkpatrick** [comment]
This is all I have for that file path?
[image: Inline image 1]


But I also have alot of directories...
[image: Inline image 2]

**Comment by eirannejad** [comment]
@joseph-kirkpatrick Images don't show up from reply to email. Comment on github.

**Comment by joseph-kirkpatrick** [comment]
Submitted

On Dec 5, 2017 4:54 PM, "Ehsan Iran-Nejad" <notifications@github.com> wrote:

@joseph-kirkpatrick <https://github.com/joseph-kirkpatrick> Images don't
show up from reply to email. Comment on github.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/eirannejad/pyRevit/issues/247#issuecomment-349454364>,
or mute the thread

**Comment by joseph-kirkpatrick** [comment]
I created a new issue, I just now seen that you had been replying on here, my apologies.

**Comment by joseph-kirkpatrick** [comment]
The wipe button is close, we need to add the unreferenced detail views. For structural we rarely use section views, it's 99.5% detail views.

**Comment by eirannejad** [comment]
There is an option for Unreferenced Drafting views. Doesn't that work?

**Comment by joseph-kirkpatrick** [comment]
Not for what we do, we have hundreds of drafting views we'll import or use
pieces of them in live sections to speed up drafting time. It's the actual
"Detail View" that you can use to make a live section that our engineers
just make and leave everywhere.

**Comment by eirannejad** [comment]
Got it. Will add to list of fixes.

**Comment by joseph-kirkpatrick** [comment]
Awesome, I'm playing around in 4.5rc now wandering around.

**Comment by eirannejad** [comment]
Added Wipe for Detail views (reference and unreferenced)
Update and test and let me know if it works.

**Comment by joseph-kirkpatrick** [comment]
I checked, and i'm not sure if the update feature is updating to show the 2 new wipe buttons.
These are all the Unreferenced views I have available. Is there a different way I have to update? As well I seen on another post, is there a way around admin privaledges needed? I have to pull a coworker every time I need anything admin/update required.

![image](https://user-images.githubusercontent.com/32959656/33732452-9aa61a36-db54-11e7-8b34-031aa276457a.png)

**Comment by eirannejad** [comment]
How did you update?

**Comment by joseph-kirkpatrick** [comment]
Just hit the update button in pyRevit. Do I need to go into the files and
do the update there?

**Comment by eirannejad** [comment]
Nope. Send me a screencap of the about menu if you don't mind. Want to check your exact version t omaek sure you're updated

**Comment by joseph-kirkpatrick** [comment]
This?
![image](https://user-images.githubusercontent.com/32959656/33737124-196aa5d6-db63-11e7-8d86-7dfb052061cf.png)

**Comment by eirannejad** [comment]
Okay so you're not updated. See the list of commits here. The `e961bc1` on the about window after version should be pointing the hash of the top commit on that page.

Does the update go smoothly?

**Comment by joseph-kirkpatrick** [comment]
https://github.com/eirannejad/pyRevit/commit/5540253176498ff96334b7c747fe17f5a55f5a25

I found the new commit there, but I don't know how to update it otherwise? (still new to git)

**Comment by joseph-kirkpatrick** [comment]
I went into the pyRevit/Release folder where the upgrade.bat file is but it wont update in the cmd line due to:

"Unhandled Exception: LibGit2Sharp.LibGit2SharpException: failed to rename lockfi
le to 'C:/ProgramData/pyRevit/pyRevit-v45rc/pyRevit/.git/index': Access is denie
d.

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in C:\projects\libgit2s
harp\LibGit2Sharp\Core\Ensure.cs:line 136
   at LibGit2Sharp.Core.Proxy.git_checkout_tree(RepositoryHandle repo, ObjectId
treeId, GitCheckoutOpts& opts) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Pro
xy.cs:line 303
   at LibGit2Sharp.Repository.CheckoutTree(Tree tree, IList`1 paths, IConvertabl
eToGitCheckoutOpts opts) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:
line 951
   at LibGit2Sharp.Repository.Checkout(Tree tree, IEnumerable`1 paths, CheckoutO
ptions options) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 939
   at LibGit2Sharp.Commands.Checkout(IRepository repository, Tree tree, Checkout
Options checkoutOptions, String refLogHeadSpec) in C:\projects\libgit2sharp\LibG
it2Sharp\Commands\Checkout.cs:line 150
   at LibGit2Sharp.Commands.Checkout(IRepository repository, Branch branch, Chec
koutOptions options) in C:\projects\libgit2sharp\LibGit2Sharp\Commands\Checkout.
cs:line 95
   at pyrevitgitservices.Program.Update(List`1 updateArgs) in C:\Users\eiranneja
d\AppData\Roaming\pyRevit\pyRevitDev\pyRevitDev\release\pyrevitgitservices\pyrev
itgitservices\Program.cs:line 78
   at pyrevitgitservices.Program.<>c.<Main>b__3_2(IEnumerable`1 cargs) in C:\Use
rs\eirannejad\AppData\Roaming\pyRevit\pyRevitDev\pyRevitDev\release\pyrevitgitse
rvices\pyrevitgitservices\Program.cs:line 29
   at Mono.Options.Command.Invoke(IEnumerable`1 arguments)
   at Mono.Options.CommandSet.Run(IEnumerable`1 arguments)
   at pyrevitgitservices.Program.Main(String[] args) in C:\Users\eirannejad\AppD
ata\Roaming\pyRevit\pyRevitDev\pyRevitDev\release\pyrevitgitservices\pyrevitgits
ervices\Program.cs:line 18
You can close this window now.
Press any key to continue . . ."

**Comment by eirannejad** [comment]
For `update.bat` to work you need to close Revit. Did you try updating through the update button in pyRevit tab?

**Comment by joseph-kirkpatrick** [comment]
I tried both, i'll try again just in case I did something wrong.

**Comment by joseph-kirkpatrick** [comment]
negative, when Revit is off, this is what I get.

![image](https://user-images.githubusercontent.com/32959656/33739764-5219c6c4-db6c-11e7-8788-d3715b0ce7ea.png)

**Comment by eirannejad** [comment]
You've got some access issues. The updater can not update the internal file structure of your git clone.

**Comment by joseph-kirkpatrick** [comment]
:''(

If I just unistalled 4.5rc and reinstalled it, would that fix it? And due to someone opening an email once, our security has gotten a lot tighter.. :/

**Comment by eirannejad** [comment]
Yes the installer always install the most recent version. Sorry for all the troubles but I think it's your user admin right that doesn't allow updating the files.

**Comment by joseph-kirkpatrick** [comment]
Happy new years! I finally got the 4.5 version in but I still cant get the wipe detail views to work. I'm not sure why it won't. Could it be because the floor plans are referenced to a sheet, but the blank reference is not on a detail page?

![image](https://user-images.githubusercontent.com/32959656/34486477-23964f2a-ef9e-11e7-9eaf-b27b1ac0fdba.png)

**Comment by eirannejad** [comment]
So there IS a reference to the view somewhere bu the view itself is not placed on any sheets? If thats the case the view IS still referenced. Would you please email me an example file so I can test?

**Comment by joseph-kirkpatrick** [comment]
Whats your email? As well I put it on a template we use however it still
didn't purge.

**Comment by eirannejad** [comment]
See on profile(left side under photo): https://github.com/eirannejad
