### ISSUE TITLE
Error when trying to upgrade pyRevit

### ISSUE THREAD

**Issue by frodooon** [eirannejad/pyRevit#289]
Hello,
I was trying to update pyRevit using the "upgrade.bat" tool in pyRevit/Release/
Exiting Revit and executing the script yields the following error:

_Updating repo at: C:\Users\cenaero\AppData\Roaming\pyRevit\pyRevit-v4\pyRevit

Unhandled Exception: LibGit2Sharp.CheckoutConflictException: 1 conflict prevents checkout
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in C:\projects\libgit2sharp\LibGit2Sharp\Co
re\Ensure.cs:line 136
   at LibGit2Sharp.Core.Proxy.git_checkout_tree(RepositoryHandle repo, ObjectId treeId, GitCheckoutO
pts& opts) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 303
   at LibGit2Sharp.Repository.CheckoutTree(Tree tree, IList`1 paths, IConvertableToGitCheckoutOpts o
pts) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 951
   at LibGit2Sharp.Repository.FastForwardMerge(AnnotatedCommitHandle annotatedCommit, MergeOptions o
ptions) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 1589
   at LibGit2Sharp.Repository.Merge(AnnotatedCommitHandle[] annotatedCommits, Signature merger, Merg
eOptions options) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 1468
   at LibGit2Sharp.Repository.MergeFetchedRefs(Signature merger, MergeOptions options) in C:\project
s\libgit2sharp\LibGit2Sharp\Repository.cs:line 1252
   at LibGit2Sharp.Commands.Pull(Repository repository, Signature merger, PullOptions options) in C:
\projects\libgit2sharp\LibGit2Sharp\Commands\Pull.cs:line 38
   at pyrevitgitservices.Program.Update(List`1 updateArgs) in C:\Users\16073\AppData\Roaming\pyRevit
\pyRevit-v4\pyRevit\release\pyrevitgitservices\pyrevitgitservices\Program.cs:line 80
   at pyrevitgitservices.Program.<>c.<Main>b__3_2(IEnumerable`1 cargs) in C:\Users\16073\AppData\Roa
ming\pyRevit\pyRevit-v4\pyRevit\release\pyrevitgitservices\pyrevitgitservices\Program.cs:line 29
   at Mono.Options.Command.Invoke(IEnumerable`1 arguments)
   at Mono.Options.CommandSet.Run(IEnumerable`1 arguments)
   at pyrevitgitservices.Program.Main(String[] args) in C:\Users\16073\AppData\Roaming\pyRevit\pyRev
it-v4\pyRevit\release\pyrevitgitservices\pyrevitgitservices\Program.cs:line 18
You can close this window now.
Press any key to continue . . ._

Thanks for any help!
Arnaud.

**Comment by eirannejad** [comment]
Seems like there's been some changes to the installed pyRevit. Could be filestamp changes that's throwing git off. I'd suggest uninstalling any version < 4.5 and installing fresh.

**Comment by frodooon** [comment]
Thank you!
Did it, and I see you suggested that on the pyRevit page, sorry I missed that!
But I have now another problem at startup:

_ERROR: [pyrevit.coreutils.ribbon] Error adding icon for Basics from E:/.../Basics.pushbutton/icon.png | Error in applying icon to button > E:/.../Basics.pushbutton/icon.png : No imaging component suitable to complete this operation was found.

Traceback:
 File "C:/Users/cenaero/AppData/Roaming/pyRevit/pyRevit-v45/pyRevit/pyrevitlib/pyrevit/coreutils/ribbon.py", line 838, in create_push_button
 new_button.set_icon(icon_path, icon_size=ICON_LARGE)_

The icon is there, and it was working before.. Any idea?
Thanks again!

**Comment by eirannejad** [comment]
Check the icon size for your tool. It shouldn't be larger than 96x96. This usually happens on very large icons

**Comment by salvodragotta** [comment]
Hi,

Sorry if I jump in. I  used the "upgrade.bat" tool ass well. When I load Revit a het the error:

"Failed to initialize the add-in...PyReviloader.dll does not exist".

So should I do a fresh install as well?

if I do that, is the conflict with Dynamo being fixed?
https://github.com/eirannejad/pyRevit/issues/231

Thanks!

![image](https://user-images.githubusercontent.com/8536282/35783417-c9be1064-0a5a-11e8-87fb-4f496540e28c.png)

![image](https://user-images.githubusercontent.com/8536282/35783418-cb77eede-0a5a-11e8-84a0-331826420cd3.png)

**Comment by eirannejad** [comment]
http://eirannejad.github.io/pyRevit/pyrevit/update/2018/01/01/45final.html
See note on installation. There has been a change to the location of pyRevitLoader.dll. You need to run the addin creator batch script to correct the Revit addin manifest files.

**Comment by eirannejad** [comment]
I updated the `upgrade.bat` script to call the other two after update. Pushed to develop branch and will be merge to master on next merge.

**Comment by eirannejad** [comment]
Merged
