### ISSUE TITLE
Bug when executing Wipe Model Components tool

### ISSUE THREAD

**Issue by che-30** [eirannejad/pyRevit#305]
Bug when executing Wipe Model Components tool

```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\user05\AppData\Roaming\pyRevit\pyRevit-v4\pyRevit\extensions\pyRevitTools.extension\pyRevit.tab\Project.panel\Wipe.pulldown\Wipe Model Components.pushbutton\script.py", line 51, in 
 File "C:\Users\user05\AppData\Roaming\pyRevit\pyRevit-v4\pyRevit\extensions\pyRevitTools.extension\lib\pyrevittoolslib\wipeactions.py", line 804, in get_worksetcleaners
 File "C:\Users\user05\AppData\Roaming\pyRevit\pyRevit-v4\pyRevit\extensions\pyRevitTools.extension\lib\pyrevittoolslib\wipeactions.py", line 780, in copy_func
NotImplementedError: The method or operation is not implemented.

Script Executor Traceback:
System.NotImplementedException: The method or operation is not implemented.
 at Microsoft.Scripting.Interpreter.NewInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run8[T0,T1,T2,T3,T4,T5,T6,T7,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute7[T0,T1,T2,T3,T4,T5,T6,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`10.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run8[T0,T1,T2,T3,T4,T5,T6,T7,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
 at IronPython.Compiler.Ast.CallExpression.Invoke5Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`7.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run5[T0,T1,T2,T3,T4,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
 at IronPython.Compiler.Ast.CallExpression.Invoke2Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)
```

Revit execution with both parameter /eng and /rus leads to this result

**Comment by eirannejad** [comment]
What’s “Bag”?

**Comment by che-30** [comment]
)))
sorry

**Comment by che-30** [comment]
bug

**Comment by eirannejad** [comment]
Haha okay I'll look into it

**Comment by eirannejad** [comment]
Resolved. Please update to latest.
for the purpose of documentation:
This issue occurred on IronPython 2.7.3 since it does not support function duplication. The code was creating wipe function for each workset type. The tool and the code behind were modified to allow function reuse with different arguments.

**Comment by eirannejad** [comment]
😂 most welcome
