### ISSUE TITLE
Question : Any known issue with " clr.Reference[Family]() " in Pyrevit

### ISSUE THREAD

**Issue by varunbose** [eirannejad/pyRevit#307]
Hi all,

Is there any issue with `clr.Reference[Family]()` in Pyrevit...?

The code below works in RPS, but returns following error in Pyrevit.

```
import clr
import rpw
import Autodesk.Revit.DB as DB
from Autodesk.Revit.DB import Transaction

family_elem = clr.Reference[Family]()
path = r'C:\ProgramData\Autodesk\RVT 2016\Libraries\Australia\Furniture\TV Stand.rfa'

t = Transaction(doc, 'Loadfamily')
t.Start()
try:
    success, family_elem = doc.LoadFamily.Overloads.Functions[0](path)
    print family_elem
    t.Commit()
except:
    t.Rollback()
```
**Error**

```
Script Executor Traceback:
IronPython.Runtime.UnboundNameException: name 'Family' is not defined
 at IronPython.Runtime.Operations.PythonOps.GetVariable(CodeContext context, String name, Boolean isGlobal, Boolean lightThrow)
 at IronPython.Compiler.LookupGlobalInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)
```
Please help

**Comment by eirannejad** [comment]
You're referencing a symbol (Family) that has not been defined in your code.

It should either be imported
``` python
from Autodesk.Revit.DB import Family
```
or referenced by imported namespace
``` python
import Autodesk.Revit.DB as DB

DB.Family
```

It works in RPS because RPS has an initializer code that imports everything from DB namespace into the code. However this is not good practice. It makes sense in RPS since it is a shell and it needs to be ready-to-go.

**Comment by varunbose** [comment]
Thanks Eshan,
I appreciate your prompt replies on all posts...

Great work mate...
