### ISSUE TITLE
Duplicate multiple views error

### ISSUE THREAD

**Issue by oooarch** [eirannejad/pyRevit#309]
Hi,

I am trying out v4.5 in RVT 2017(build: 20170816_0615(x64) (Windows 10). I am having an issue with the ones related to batch duplication of views (the same also applies to batch renaming, printing). It does not recognise multiple selections on the project browser, it either only duplicates just one view or gives this error: ﻿

```
ERROR: [pyrevit.revit.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:View cannot be duplicated

IronPython Traceback:
Traceback (most recent call last):
 File "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\views.stack3\Views.pulldown\Duplicate Selected Views.pushbutton\script.py", line 31, in 
 File "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\views.stack3\Views.pulldown\Duplicate Selected Views.pushbutton\script.py", line 14, in duplicate_views
Exception: View cannot be duplicated

Script Executor Traceback:
Autodesk.Revit.Exceptions.InvalidOperationException: View cannot be duplicated
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run5[T0,T1,T2,T3,T4,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)
```

I have tried the same version of pyrevit with RVT 2018 and the issue did not occur. Hope you can point me in the right direction to solve this.

Thanks.

**Comment by eirannejad** [comment]
What view are you trying to duplicate? It says `Exception: View cannot be duplicated`

**Comment by oooarch** [comment]
Any view. I think I have narrowed down more the issue. The tool only recognises the active view on the project browser. So when I select multiple ones it only duplicates the active one. In the case of the error It is when a sheet is the active view.

**Comment by eirannejad** [comment]
Hmm okay I’ll look into it today

**Comment by oooarch** [comment]
Thanks. I hope I have been able to make it clear enough.

**Comment by eirannejad** [comment]
Okay I figured out what is the issue and will fix and push soon. Will update you when ready

**Comment by eirannejad** [comment]
Done. Now you get a view selector window on all tools that need selected views.

![2018-03-02 16_41_59-select views](https://user-images.githubusercontent.com/8197916/36928202-a67ff242-1e38-11e8-8380-d751c2e946e2.png)

**Comment by oooarch** [comment]
Brilliant! Thanks.
