### ISSUE TITLE
Error with convert Drafting to Legend

### ISSUE THREAD

**Issue by themindisaterriblethingtotaste** [eirannejad/pyRevit#395]
same error with both pyrevit 4.5 and 4.6-beta3, error saying "View cannot be duplicated"
using Revit 2018.3.1
this worked ok in older versions on pyrevit. I'm new to all this so not really sure what any of this means

﻿

ERROR: [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:View cannot be duplicated

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\elton.williams\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\views.stack3\Legends.pulldown\Convert Drafting to Legend.pushbutton\script.py", line 58, in 
Exception: View cannot be duplicated

Script Executor Traceback:
Autodesk.Revit.Exceptions.InvalidOperationException: View cannot be duplicated
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)

**Comment by SylviaQB** [comment]
Was this ever resolved, running into the same issue here.

﻿


ERROR: [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:View cannot be duplicated


IronPython Traceback:
Traceback (most recent call last):
 File "C:\Program Files\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\views.stack3\Legends.pulldown\Convert Drafting to Legend.pushbutton\script.py", line 58, in 
Exception: View cannot be duplicated


Script Executor Traceback:
Autodesk.Revit.Exceptions.InvalidOperationException: View cannot be duplicated
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)
