### ISSUE TITLE
Unicode in charts

### ISSUE THREAD

**Issue by epeter-** [eirannejad/pyRevit#398]
my script is using german revit categories as labels for charts. my script uses:

"# -*- coding: utf-8 -*-"
in the first line of code (without "" - this is just to avoid formating)
errormessage  is:

```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit\extensions\KOP.extension\KOP.tab\Auswertungen.panel\Auswertungen.splitbutton\AW2.pushbutton\STLB berechnen_script.py", line 526, in 
 File "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit\pyrevitlib\pyrevit\coreutils\charts\__init__.py", line 178, in draw
 File "json\encoder.py", line 408, in _iterencode_dict
 File "json\encoder.py", line 313, in _iterencode_list
 File "json\encoder.py", line 47, in py_encode_basestring_ascii
 File "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit\pyrevitlib\pyrevit\coreutils\charts\__init__.py", line 150, in _make_charts_script
 File "json\encoder.py", line 209, in encode
 File "json\encoder.py", line 443, in _iterencode
 File "json\encoder.py", line 434, in _iterencode
 File "json\encoder.py", line 408, in _iterencode_dict
 File "json\encoder.py", line 443, in _iterencode
 File "json\encoder.py", line 434, in _iterencode
UnicodeDecodeError: ('unknown', u'\xe4', 0, 1, '')
```

# so my question is how to use automatically generated unicode strings in charts?

**Comment by epeter-** [comment]
for processing a list the conversion is as simple as:
`str = str.encode('utf8')`
