### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'GetEngines'

### ISSUE THREAD

**Issue by tmsz** [eirannejad/pyRevit#407]
When clicking Settings I have this problem:

    IronPython Traceback:
    Traceback (most recent call last):
     File "C:\Users\---\AppData\Roaming\pyRevit-Master\extensions\pyRevitCore.extension\pyRevit.tab\pyRevit.panel\Settings.smartbutton\script.py", line 448, in 
     File "C:\Users\---\AppData\Roaming\pyRevit-Master\extensions\pyRevitCore.extension\pyRevit.tab\pyRevit.panel\Settings.smartbutton\script.py", line 55, in __init__
     File "C:\Users\---\AppData\Roaming\pyRevit-Master\extensions\pyRevitCore.extension\pyRevit.tab\pyRevit.panel\Settings.smartbutton\script.py", line 112, in _setup_engines
    AttributeError: 'NoneType' object has no attribute 'GetEngines'
    
    
    Script Executor Traceback:
    System.MissingMemberException: 'NoneType' object has no attribute 'GetEngines'
     at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
     at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
     at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
     at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
     at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
     at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
     at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
     at IronPython.Runtime.Method.MethodBinding.SelfTarget(CallSite site, CodeContext context, Object target)
     at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
     at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
     at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
     at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
     at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
     at IronPython.Runtime.Types.LateBoundInitBinder.FastInitSite`1.CallTarget(CallSite site, CodeContext context, Object inst, T0 arg0)
     at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
     at IronPython.Runtime.Types.PythonType.FastTypeSite`1.CallTarget(CallSite site, CodeContext context, Object type, T0 arg0)
     at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
     at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
     at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
     at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
     at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
     at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)

**Comment by eirannejad** [comment]
Which pyRevit version?

**Comment by tmsz** [comment]
PyRevit 4.6.5,  Revit 2018.3

**Comment by eirannejad** [comment]
Okay I'm assuming you installed using the installer. Would you please open a command prompt and run this and send me the results? It helps me see why the settings tool is not seeing your clone.
`pyrevit env`

**Comment by tmsz** [comment]
Microsoft Windows [Version 10.0.17134.345]
    (c) 2018 Microsoft Corporation. Wszelkie prawa zastrzeżone.
    
    C:\Users\---\AppData\Roaming\pyRevit-Master\bin>pyrevit env
    ==> Registered Clones (full git repos)
    ==> Registered Clones (deployed from archive)
    ==> Attachments
    Error: pyRevit is attached to Revit 2018 but can not determine the clone and engine
    ==> Installed UI Extensions
    ==> Installed Library Extensions
    ==> Extension Search Paths
    ==> Extension Sources - Default
    https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
    ==> Extension Sources - Additional
    ==> Installed Revits
    Autodesk Revit 2018 First Customer Ship | Version: 18.0.0.420 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
    ==> Running Revit Instances
    PID: 2588 | Autodesk Revit 2018 First Customer Ship | Version: 18.0.0.420 | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
    
    C:\Users\---\AppData\Roaming\pyRevit-Master\bin>

**Comment by alexdaversa** [comment]
Anything to do with the latest Revit updates? I am getting the error in a recently updated Revit 2017.2.4, but not 2018.3 that I have not updated. Revit 2017.2.4 doesn't show up when running `pyrevit env`

http://blogs.autodesk.com/revit/2018/10/22/information-about-recent-security-updates/

**Comment by eirannejad** [comment]
Do you have a `.` in your `%APPDATA%` path?

**Comment by tmsz** [comment]
There is no `.` in my username and in whole path to `pyRevit-Master' directory.

**Comment by eirannejad** [comment]
Merged into: https://github.com/eirannejad/pyRevit/issues/421
