### ISSUE TITLE
Manage Keynotes breaks in 4.6.10

### ISSUE THREAD

**Issue by htlcnn** [eirannejad/pyRevit#475]
**Describe the bug**
Manage Keynotes tool failed to fire up.

**To Reproduce**
1. Install pyRevit 4.6.10, overwrite old version
2. Click on pyRevit -> Drawing Set -> Manage Keynotes
3. Exception:

```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\HTL\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Keynotes.pushbutton\script.py", line 17, in 
ImportError: Cannot import name UIDocUtils


Script Executor Traceback:
IronPython.Runtime.Exceptions.ImportException: Cannot import name UIDocUtils
 at IronPython.Runtime.Importer.ImportFrom(CodeContext context, Object from, String name)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)
```

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - pyRevit Version 4.6.10
 - pyRevit Environment:
```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
Name: "master" | Deploy: "basepublic" | Path: "C:\Users\HTL\AppData\Roaming\pyRevit-Master"
==> Attachments
Autodesk Revit 2018.3.1 | Clone: "master" | Engine: "277"
Autodesk Revit 2019.1 | Clone: "master" | Engine: "277"
Autodesk Revit 2018 First Customer Ship | Clone: "master" | Engine: "277"
Autodesk Revit 2019 First Customer Ship | Clone: "master" | Engine: "277"
==> Installed UI Extensions
Name: "htl" | Repo: "" | Installed: "...\pyRevit extensions\htl.extension"
==> Installed Library Extensions
==> Extension Search Paths
...\pyRevit extensions
...\HTL\Desktop
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2018.3.1 | Version: 18.3.1.2 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
Autodesk Revit 2019.1 | Version: 19.1.0.112 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
Autodesk Revit 2018 First Customer Ship | Version: 18.0.0.420 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit Content 2018\"
Autodesk Revit 2019 First Customer Ship | Version: 19.0.0.405 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit Content 2019\"
==> Running Revit Instances
PID: 31368 | Autodesk Revit 2018.3.1 | Version: 18.3.1.2 | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Executing User: HTL\HTL
Active User: HTL\HTL
Adming Access: No
%APPDATA%: "C:\Users\HTL\AppData\Roaming"
Latest Installed .Net Framework: "4.7.2"
pyRevit CLI 0.2.18.0
```

@eirannejad

**Comment by eirannejad** [comment]
Hey run `pyrevit caches clear --all` in terminal and let me know if it fixes the issue

**Comment by eirannejad** [comment]
What's the Revit version btw?
