### ISSUE TITLE
pyrevit MEP didn´t work example element 3d rotation in version 4.6.11

### ISSUE THREAD

**Issue by melankoma** [eirannejad/pyRevit#476]
```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Tarik\AppData\Roaming\pyRevit\Extensions\PyRevitMEP.extension\pyRevitMEP.tab\Tools.panel\Element3DRotation.pushbutton\script.py", line 140, in 
 File "C:\Users\Tarik\AppData\Roaming\pyRevit\Extensions\PyRevitMEP.extension\pyRevitMEP.tab\Tools.panel\Element3DRotation.pushbutton\script.py", line 114, in __init__
 File "C:\Users\Tarik\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 146, in set_image_source
AttributeError: 'str' object has no attribute 'Source'


Script Executor Traceback:
System.MissingMemberException: 'str' object has no attribute 'Source'
 bei CallSite.Target(Closure , CallSite , Object , Object )
 bei System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 bei Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 bei Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 bei IronPython.Compiler.PythonCallTargets.OriginalCallTarget3(PythonFunction function, Object arg0, Object arg1, Object arg2)
 bei IronPython.Runtime.Method.MethodBinding`2.SelfTarget(CallSite site, CodeContext context, Object target, T0 arg0, T1 arg1)
 bei System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 bei Microsoft.Scripting.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
 bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 bei Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 bei System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 bei IronPython.Runtime.Types.LateBoundInitBinder.FastInitSite`1.CallTarget(CallSite site, CodeContext context, Object inst, T0 arg0)
 bei System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 bei IronPython.Runtime.Types.PythonType.FastTypeSite`1.CallTarget(CallSite site, CodeContext context, Object type, T0 arg0)
 bei System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 bei Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 bei Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 bei IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 bei PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)
```

**Comment by CyrilWaechter** [comment]
Something have been changed in pyrevit and all script using images are currently not working. I asked Ehsan to know if it is a mistake or a will to change the way it works. In first case, I can't do anything, in second case I'll need to rework all script which are using set_image_source method. I'm waiting for his answer.

**Comment by eirannejad** [comment]
@CyrilWaechter Yes the `set_image_source` has been changed to be consistent with other window methods, getting the window element as argument and not its name. So:

```python
self.set_image_source("xyz_img", "XYZ.png")
```

should be changed to:

```python
self.set_image_source(self.xyz_img, "XYZ.png")
```

It's a quick fix. Should I send you a PR?

**Comment by eirannejad** [comment]
@melankoma As a temp solution you can run a search through the source for `self.set_image_source` and revise the code until the source repo is updated.

**Comment by CyrilWaechter** [comment]
@eirannejad I patched my scripts to take into account the new method behaviour. 

@melankoma Please update pyRevitMEP. Thanks for the report !
Next time please if it is related to pyRevitMEP open an issue on project repo : https://github.com/CyrilWaechter/pyRevitMEP/issues

**Comment by eirannejad** [comment]
Thanks @CyrilWaechter
