### ISSUE TITLE
pyRevit cannot load python2.7 libraries

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#481]
I have created a simple pyRevit extension like in your tutorial (a button, that once clicked calculates the total volume of all objects in the model). I now want to use python modules, that I have installed with Anaconda2. **This is possible, right ?** 

For instance, I type this script inside the _extension_ for pyRevit, then push the button. 
```
from shapely.geometry import Point
p = Point(1,2)
print("that's my point! %s " % p.to_wkt())
```

I get this error. 
```
ImportError: No module named shapely.geometry

Script Executor Traceback:
IronPython.Runtime.Exceptions.ImportException: No module named shapely.geometry
 at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
 at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)
```

In the RevitPythonShell I tried to do the same, having a (somehow) easier to understand error: I am missing the path to the DLLs (will try to see how to do that). 
```
>>> from shapely.geometry import Point
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\angelo\Anaconda2\Lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
  File "C:\Users\angelo\Anaconda2\Lib\site-packages\shapely\geometry\base.py", line 17, in <module>
  File "C:\Users\angelo\Anaconda2\Lib\site-packages\shapely\coords.py", line 8, in <module>
  File "C:\Users\angelo\Anaconda2\Lib\site-packages\shapely\geos.py", line 148, in <module>
  File "C:\Users\angelo\Anaconda2\Lib\site-packages\shapely\geos.py", line 54, in load_dll
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
```

I tried to update my environment variables (`PATH` and/or `PYTHONPATH`) and then update the system path in python before running scripts in Revit, this way
```
# PYTHONPATH updated to add C:/Users/angelo/Anaconda2/Lib/site-package
import os, sys
sys.path.append(os.environ["PATH"])
sys.path.append(os.environ["PYTHONPATH"])
```
But it didn't change things. For RevitPythonShell I updated the "Search Paths" of its configuration to have those directories in, and still nothing.

**Comment by eirannejad** [comment]
No you can't. You're technically creating **IronPython** scripts. It's the implementation of python on dotnet framework and is the only implementation that can talk to Revit. Some standard python modules work on IronPython as well but a lot of python modules use c binaries for performance. None of those modules e.b. numpy would work with IronPython.

Instead of adding `PATH` and `PYTHONPATH`, try adding the modules path directly. Remember the value of `PATH` is a `;`-separated string not an actual path.

```python
import sys
sys.path.append(r'C:\...\path\to\site-packages')
```
