### ISSUE TITLE
load/reload failing - "'PyRevitException' object has no attribute 'lineno'"

### ISSUE THREAD

**Issue by MatthewJohnsonVMDO** [eirannejad/pyRevit#523]
Edit: before you read all this, I found the specific cause of this problem and commented below

I've tried to add a new command "Demo.pushbutton" to a custom extension that I've created.  If I delete the "Demo.pushbutton" folder, pyRevit loads as expected, including my custom extension.  If I put it back, I get the error below.  My apologies for not providing more information, I'm pretty new to programming so the traceback is somewhat beyond me.  

-OS: Windows 7 Professional SP1
 - pyRevit Version 4.6.5

![pyrevit bug folder](https://user-images.githubusercontent.com/47393355/52641496-ff0cf980-2ea6-11e9-8db4-829346c755f5.PNG)
![pyrevit bug traceback](https://user-images.githubusercontent.com/47393355/52641497-ffa59000-2ea6-11e9-8b5a-faabe9148527.PNG)
![pyrevit environment](https://user-images.githubusercontent.com/47393355/52641717-7b074180-2ea7-11e9-9769-b254d1aae42a.PNG)

```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\extensions\pyRevitCore.extension\pyRevit.tab\pyRevit.panel\tools.stack3\Reload.pushbutton\script.py", line 37, in 
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py", line 227, in load_session
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py", line 150, in _new_session
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\extensions\extensionmgr.py", line 204, in get_installed_ui_extensions
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\extensions\extensionmgr.py", line 91, in _parse_or_cache
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\extensions\parser.py", line 115, in get_parsed_extension
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\extensions\parser.py", line 99, in _parse_for_components
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\extensions\parser.py", line 99, in _parse_for_components
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\extensions\parser.py", line 90, in _parse_for_components
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\extensions\parser.py", line 69, in _create_subcomponents
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\extensions\parser.py", line 26, in _get_discovered_comps
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\extensions\genericcomps.py", line 324, in __init_from_dir__
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\extensions\genericcomps.py", line 414, in _analyse_python_script
 File "C:\Users\Matthew-j\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\extensions\genericcomps.py", line 354, in _handle_parse_err
AttributeError: 'PyRevitException' object has no attribute 'lineno'


Script Executor Traceback:
System.MissingMemberException: 'PyRevitException' object has no attribute 'lineno'
 at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
 at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at IronPython.Compiler.Ast.CallExpression.Invoke2Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`7.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run5[T0,T1,T2,T3,T4,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
 at IronPython.Compiler.Ast.CallExpression.Invoke2Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`6.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
 at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
 at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)
```

**Comment by MatthewJohnsonVMDO** [comment]
Update: this error appears to be caused by the "Demo.pushbutton" script, which I've copied below.  If I change the script to nothing or a copy/paste of a working script, pyRevit loads as expected.  

`__title__ = 'Template' #Name that appears with icon in Revit ribbon
__doc__ = 'This is a new button' #text that will appear when the user hovers over the button
__author__ = 'Matt Johnson' #will also appear in hovertext
__context__ = selection #determines availability of the button - see "pyRevit Script Anatomy"

#do any imports here, don't import RevitNodes!
from pyrevit.framework import clr
from pyrevit import revit, DB



t=Transaction(doc,"NewCommand")
t.Start()

#Put any modifications to the Revit model here

t.Commit()
`

**Comment by eirannejad** [comment]
You da man! :D

**Comment by fazacz** [comment]
I've change button name by `__title__ = '{Some cyrillic string}'` in copied pyRevit's "Find And Select Entities Without Tags" script and got same error. I've even tried paste `# -*- coding: utf-8 -*-` in head, this didnt help. In other scripts, that wrote myself, it works fine.
Then I opened file in Notepad3 instead of Sublime Text 3 and saw some coding trouble.
Sublime Text 3: `__title__ = 'Где нет\nмарок?'`.
Notepad3: `__title__ = 'ä堭岜n젰'`.
Problem was solved by 

> File -> Save with Encoding -> UTF-8


 in Sublime Text 3.

![2019-06-27_11-45-43](https://user-images.githubusercontent.com/48551849/60251495-4d102000-98d1-11e9-8122-138fa50b4a90.png)

**Comment by eirannejad** [comment]
Yes. Save your scripts in UTF-8 when using unicode characters especially when directing python that your script is in utf-8 with `# -*- coding: utf-8 -*-`
