### ISSUE TITLE
windows.form.radiobutton crash when launched from pyRevit

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#569]
Dear Ehsan, 

I have launched a little windows form from a pyRevit button. It contains radio buttons, and normally the behaviour should be: "when you check one of them, the others become unchecked". 

This code (at the bottom of this post) works if run from `python radios.py` in a windows command line. But crashes from pyRevit as soon as I check the second radio button. 

error: `Absolute path information is required`

details: 
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Absolute path information is required.
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Windows.Forms.Control.ControlVersionInfo.GetFileVersionInfo()
   at System.Windows.Forms.Control.ControlVersionInfo.get_CompanyName()
   at IronPython.NewTypes.System.Windows.Forms.RadioButton_22$22.#base#get_CompanyName()
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
   at IronPython.Runtime.Types.BuiltinFunction.Call0(CodeContext context, SiteLocalStorage`1 storage, Object instance)
   at IronPython.Runtime.Types.ReflectedProperty.CallGetter(CodeContext context, PythonType owner, SiteLocalStorage`1 storage, Object instance)
   at IronPython.Runtime.Types.ReflectedProperty.TryGetValue(CodeContext context, Object instance, PythonType owner, Object& value)
   at IronPython.Runtime.Types.PythonType.TryGetNonCustomMember(CodeContext context, Object instance, String name, Object& value)
   at IronPython.Runtime.Operations.PythonOps.ObjectGetAttribute(CodeContext context, Object o, String name)
   at IronPython.Runtime.Operations.CustomTypeDescHelpers.GetPropertiesImpl(Object self, Attribute[] attributes)
   at IronPython.Runtime.Operations.CustomTypeDescHelpers.GetProperties(Object self)
   at System.ComponentModel.TypeDescriptor.MergedTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetProperties()
   at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
   at System.Windows.Forms.RadioButton.PerformAutoUpdates(Boolean tabbedInto)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at IronPython.NewTypes.System.Windows.Forms.RadioButton_22$22.OnClick(EventArgs e)
   at System.Windows.Forms.RadioButton.OnMouseUp(MouseEventArgs mevent)
   at IronPython.NewTypes.System.Windows.Forms.RadioButton_22$22.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at IronPython.NewTypes.System.Windows.Forms.RadioButton_22$22.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Can you tell me what piece of code I need in order not to make revit throw this error?**

Thank you 

"radios.py (inside pushbutton)"
```python
# Windows utilities and IronPython stuff
import clr
clr.AddReference("System.Drawing")
import System.Drawing as wdrawing
clr.AddReference("System.Windows.Forms")
import System.Windows.Forms as wforms


class RoadRadioButton(wforms.RadioButton):

    def __init__(self, name, radios_collection):

        self.radios_collection = radios_collection
        
        self.Text = name
        self.MouseHover += self.onMouseHover
        self.MouseLeave += self.onMouseLeave
        self.CheckedChanged += self.checkedChanged
        print("init %s" % self.Text)

    def onMouseHover(self, sender, args):
        print("onMouseHover %s " % self.Text)

    def onMouseLeave(self, sender, args):
        print("onMouseLeave %s " % self.Text)

    def checkedChanged(self, sender, args):
        print("checkedChanged %s " % self.Text)



class RadiosForm(wforms.Form):
    
    def __init__(self, *args, **kwargs):

        self.Text = "" if "title" not in kwargs else kwargs["title"]
        self.num = 1 if "num" not in kwargs else int(kwargs["num"])

        self.AutoSize = True
        #self.Location = wdrawing.Point(20,20)

        print("init %s " % self.Text)

        # creation of a title
        l = wforms.Label()
        l.Text = "Init radio form: list of buttons:"
        l.AutoSize = True
        l.Location = wdrawing.Point(10, 10)
        self.lab_intro = l
        self.Controls.Add(self.lab_intro)


        # addition of all radios with events 
        self.radios = list()
        lineno, height = 20, 25
        for i in range(1, self.num+1):
            rbname = "radio %d" % i
            print("\t\tprocessing %s" % rbname)
            rb = RoadRadioButton(rbname, self.radios)
            rb.Location = wdrawing.Point(30, lineno + height)
            rb.AutoCheck = True
            rb.AutoSize = True
            self.radios.append(rb)
            self.Controls.Add(self.radios[len(self.radios)-1])
            lineno += height


        # cancel button
        b = wforms.Button()
        b.Text = "Cancel"
        b.Height = 30
        b.Width = 100
        b.Location = wdrawing.Point(170,310)
        b.Click += self.close
        self.btn_cancel = b
        self.Controls.Add(self.btn_cancel)

    def close(self, sender=None, args=None):
        print(">>> closing %s" % self.Text)
        self.Dispose()


f = RadiosForm(title="Radios Form", num=5)
f.ShowDialog() # this is blocking: the pyrevit script is still alive until the form is closed

```

**Comment by eirannejad** [comment]
I'm looking into it but just out of curiosity why are you using WinForm instead of WPF?

**Comment by amastrobera** [comment]
I tried WPF but I was struggling and getting errors. The WinForm worked straight away and had a rich documentation, so I went on and quickly developed a series of forms/dialogs for my plugins ... until this error for the radios.

**Comment by eirannejad** [comment]
Same happens for me in IronPython independent execution. There are a couple of online links relating this to the runtime bugs.

![2019-04-04 09_06_43- 1_3  Cmder](https://user-images.githubusercontent.com/8197916/55570834-1bfcc680-56b9-11e9-950d-138be2e0555c.png)

**Comment by eirannejad** [comment]
RE https://social.msdn.microsoft.com/Forums/en-US/b18100d6-369c-487f-9820-41c406b398f1/windowsformsratiobutton-crashes-when-i-select-the-second-button-from-a-list?forum=winforms

**Comment by eirannejad** [comment]
I'm closing since this is not a pyRevit issue and seems to be a runtime bug but feel free to continue the conversation.

**Comment by amastrobera** [comment]
> RE https://social.msdn.microsoft.com/Forums/en-US/b18100d6-369c-487f-9820-41c406b398f1/windowsformsratiobutton-crashes-when-i-select-the-second-button-from-a-list?forum=winforms

yes that's me still. Ok, i'll try to get some help from IronPython if any

**Comment by eirannejad** [comment]
I know. Added the link there for reference.

**Comment by amastrobera** [comment]
I found out actually. By using the base class `wforms.RadioButton()` instead of my derived class, it all works. This means that the events are managed by the parent form. I also put all these into a Panel() (there exists a RadioBox() object too, but it's annoying that its border cannot be deleted, so panel it was for me)
