### ISSUE TITLE
Move Selected Viewports to Selected Sheet

### ISSUE THREAD

**Issue by iumepock** [eirannejad/pyRevit#629]
Command failed.

```﻿
ERROR: [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.AttributeError'>:'View' object has no attribute 'DeleteViewport'


IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Rodrigo\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Sheets.pulldown\Move Selected Viewports To Selected Sheet.pushbutton\script.py", line 32, in 
AttributeError: 'View' object has no attribute 'DeleteViewport'


Script Executor Traceback:
System.MissingMemberException: 'View' object has no attribute 'DeleteViewport'
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)```

**Comment by eirannejad** [comment]
Your active view must be a sheet

**Comment by eirannejad** [comment]
Fixed and will be published with next release
