### ISSUE TITLE
Managed antivirus quarantines on install

### ISSUE THREAD

**Issue by admiralarcharch** [eirannejad/pyRevit#741]
Our network admin's antivirus quarantines during the install of CLI_0.16.0.0 and the new beta and fails.

C:\Users\[USER]\AppData\Roaming\Ehsan Iran-Nejad\pyRevit CLI 0.16.0.0\install\FA435E8\pyrevit-toast.exe is malware of type Gen:Variant.Razy.569148

**Comment by eirannejad** [comment]
Hmm... What's your antivirus?

**Comment by admiralarcharch** [comment]
SolarWinds maybe?  Our IT providor was able to whitelist it, but something changed in the new version for the antivirus to pick it up.  It installs correctly now but will not load in Revit.  In a command prompt I run:

C:\Users\admiralarcharch>pyrevit attach master 277 --installed
Error: Can not find clone "master"
Run with "--debug" option to see debug messages

```
C:\Users\admiralarcharch>pyrevit attach master 277 --installed --debug
<clone_name> = master
attach = True
<engine_version> = 277
--installed = True
Debug: Checking for all: wiki
Debug: Missing: wiki
Debug: Checking for all: blog
Debug: Missing: blog
Debug: Checking for all: docs
Debug: Missing: docs
Debug: Checking for all: source
Debug: Missing: source
Debug: Checking for all: youtube
Debug: Missing: youtube
Debug: Checking for all: support
Debug: Missing: support
Debug: Checking for all: env
Debug: Missing: env
Debug: Checking for all: update
Debug: Missing: update
Debug: Checking for all: clone
Debug: Missing: clone
Debug: Checking for all: clones
Debug: Missing: clones
Debug: Checking for all: attach
Debug: Try getting config as dict "environment:clones"
Debug: Try getting config "environment:clones"
Debug: Config "environment:clones" = "{}"
Debug: Updating config "environment:clones = {}"
Debug: Saving config file "C:\Users\admiralarcharch\AppData\Roaming\pyRevit\pyRevit_config.ini"
Error: Can not find clone "master" (pyRevitLabs.Common.PyRevitException)
   at pyRevitLabs.PyRevit.PyRevitClones.GetRegisteredClone(String cloneNameOrRepoPath)
   at pyRevitCLI.PyRevitCLICloneCmds.AttachClone(String cloneName, Boolean latest, Boolean dynamoSafe, String engineVersion, String revitYear, Boolean installed, Boolean attached, Boolean allUsers)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)
```

**Comment by eirannejad** [comment]
Okay thanks for the feedback. I have scanned the installer files using my Symantec antivirus to no avail. I'll keep an eye on these
