### ISSUE TITLE
ImportError: SEHException

### ISSUE THREAD

**Issue by martinservold** [eirannejad/pyRevit#779]
We occasionally get errors like below when running scripts, but it feels like it happens randomly and breaks in a different place each time with the same error message.

```
IronPython Traceback:
Traceback (most recent call last):
 File "K:\ACAD_ME\ME-pyRevit\PyBIM\Mega BIM.extension\Mega BIM.tab\Model Setup.panel\Place Views on Sheets.pulldown\Place Views on Sheets (Export).pushbutton\script.py", line 7, in 
 File "K:\ACAD_ME\ME-pyRevit\pyRevit-v45\pyRevit\pyrevitlib\rpw\__init__.py", line 36, in 
 File "K:\ACAD_ME\ME-pyRevit\pyRevit-v45\pyRevit\pyrevitlib\rpw\db\__init__.py", line 19, in 
 File "K:\ACAD_ME\ME-pyRevit\pyRevit-v45\pyRevit\pyrevitlib\rpw\db\view.py", line 10, in 
 File "K:\ACAD_ME\ME-pyRevit\pyRevit-v45\pyRevit\pyrevitlib\rpw\db\collector.py", line 35, in 
 File "K:\ACAD_ME\ME-pyRevit\pyRevit-v45\pyRevit\pyrevitlib\rpw\ui\__init__.py", line 1, in 
 File "K:\ACAD_ME\ME-pyRevit\pyRevit-v45\pyRevit\pyrevitlib\rpw\ui\forms\__init__.py", line 23, in 
 File "K:\ACAD_ME\ME-pyRevit\pyRevit-v45\pyRevit\pyrevitlib\rpw\ui\forms\console.py", line 33, in 
ImportError: SEHException: External component has thrown an exception.
```

The line in question is usually just a normal import:
`import inspect`

Restarting Revit did not help, but restarting my computer fixed it.

I haven't been able to find much online regarding this error.
Any thoughts on what may cause this or anything else to check when it next happens?

**Comment by eirannejad** [comment]
I'm assuming these scripts print some output to the pyRevit output window right? OR do they create their own GUI?

**Comment by martinservold** [comment]
This particular script has no GUI, it just creates an excel file based on model information and opens it. 
We've also had this error happen for scripts that use forms.alert as their only GUI.

Sometimes this error happens at pyrevit setup and shows up like this:
![SEHERROR](https://user-images.githubusercontent.com/44454303/71362931-24ee3a80-255d-11ea-881e-72b5cc362428.jpg)

**Comment by eirannejad** [comment]
I'm gonna close this for now until we have more info. Upcoming pyRevit 4.8 uses a modern C# compiler so I'm hoping we see less issues like this

**Comment by martinservold** [comment]
It seems to be a network related issue we've switched a few of our users to run the scripts on their local machines and it hasn't happened for them so far. 
When it does happen for other users, they can still open the files in question (both the script file and the import file it's failing on), so it is a very strange error indeed.
Fingers crossed the C# update.
