### ISSUE TITLE
pyRevit does not load in Revit

### ISSUE THREAD

**Issue by kraftwerk15** [eirannejad/pyRevit#805]
**Describe the bug**
Try to use new features from Release build. Install new from 4.7.4 release build page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.7.4
 - pyRevit Environment: 

```C:\Users\user>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.4" | Path: "C:\Users\user\AppData\Roaming\pyRevit-Master"
Error: Could not load file or assembly 'pyRevitLabs.TargetApps.Revit, Version=0.17.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
Run with "--debug" option to see debug messages
```

pyRevit env --debug

```
C:\Users\user>pyrevit env --debug
env = True
Debug: Checking for all: wiki
Debug: Missing: wiki
Debug: Checking for all: blog
Debug: Missing: blog
Debug: Checking for all: docs
Debug: Missing: docs
Debug: Checking for all: source
Debug: Missing: source
Debug: Checking for all: youtube
Debug: Missing: youtube
Debug: Checking for all: support
Debug: Missing: support
Debug: Checking for all: env
==> Registered Clones (full git repos)
Debug: Try getting config as dict "environment:clones"
Debug: Try getting config "environment:clones"
Debug: Config "environment:clones" = "{"master":"C:\\Users\\user\\AppData\\Roaming\\pyRevit-Master"}"
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Searching for valid clones above: C:\Users\user\AppData\Roaming\pyRevit-Master
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Checking pyRevit clone validity "C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Checking clone validity by directory structure...
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib"
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit"
Debug: Checking pyRevit path "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit"
Debug: Checking clone validity by git repo...
Debug: Valid pyRevit clone "C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Valid clone found at: C:\Users\user\AppData\Roaming\pyRevit-Master
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Checking pyRevit clone validity "C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Checking clone validity by directory structure...
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib"
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit"
Debug: Checking pyRevit path "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit"
Debug: Checking clone validity by git repo...
Debug: Valid pyRevit clone "C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Verified clone "master=C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Updating config "environment:clones = {"master":"C:\\Users\\user\\AppData\\Roaming\\pyRevit-Master"}"
Debug: Saving config file "C:\Users\user\AppData\Roaming\pyRevit\pyRevit_config.ini"
==> Registered Clones (deployed from archive/image)
Debug: Reading image clone parmeters from "C:\Users\user\AppData\Roaming\pyRevit-Master\.pyrevitargs"
Debug: Image Path: ""
Debug: Branch: "master"
Debug: Deployment: "basepublic"
Debug: "core" : "["bin", "pyrevitlib", "site-packages", "pyRevitfile"]"
Debug: "corex" : "["bin", "extensions/pyRevitCore.extension", "extensions/pyRevitRun.run", "extensions/extensions.json", "pyrevitlib", "site-packages", "pyRevitfile"]"
Debug: "base" : "["bin", "extensions/pyRevitCore.extension", "extensions/pyRevitTags.extension", "extensions/pyRevitTools.extension", "extensions/extensions.json", "pyrevitlib", "site-packages", "pyRevitfile"]"
Debug: "basepublic" : "["bin", "extensions/pyRevitCore.extension", "extensions/pyRevitRun.run", "extensions/pyRevitTags.extension", "extensions/pyRevitTools.extension", "extensions/pyRevitTutor.extension", "extensions/extensions.json", "pyrevitlib", "site-packages", "pyRevitfile"]"
Debug: "basex" : "["bin", "extensions", "pyrevitlib", "site-packages", "pyRevitfile"]"
Debug: Reading image clone parmeters from "C:\Users\user\AppData\Roaming\pyRevit-Master\.pyrevitargs"
Debug: Image Path: ""
Debug: Branch: "master"
Debug: Deployment: "basepublic"
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Checking pyRevit clone validity "C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Checking clone validity by directory structure...
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib"
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit"
Debug: Checking pyRevit path "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit"
Debug: Checking clone validity by git repo...
Debug: Valid pyRevit clone "C:\Users\user\AppData\Roaming\pyRevit-Master"
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib"
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit"
Debug: Normalized as "C:\Users\user\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\version"
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.4" | Path: "C:\Users\user\AppData\Roaming\pyRevit-Master"
Error: Could not load file or assembly 'pyRevitLabs.TargetApps.Revit, Version=0.17.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. (System.IO.FileNotFoundException)
   at pyRevitCLI.PyRevitCLICloneCmds.PrintAttachments(Int32 revitYear)
   at pyRevitCLI.PyRevitCLIAppCmds.MakeEnvReport(Boolean json)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)

**Comment by eirannejad** [comment]
Seems like your installation is missing the `pyRevitLabs.TargetApps.Revit` dll. Try reinstalling. I have seen this issue before and a reinstall usually fixes the issue

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/796

**Comment by kraftwerk15** [comment]
@eirannejad After running a Repair on the installation all files redownloaded correctly.

**Comment by eirannejad** [comment]
Sweet. Sorry for this issue. I have been trying to resolve this but it's such a heisenbug. It only affect certain machines.
