### ISSUE TITLE
Renumber Crash

### ISSUE THREAD

**Issue by jrigal31** [eirannejad/pyRevit#833]
Good morning, sir,

I would like to contact you in order to submit an error report on the use of PYrevit renumbering.
Thank you for your assistance.
Jacques.

Bonjour,

Je me permets de vous joindre afin de vous soumettre un rapport d'erreur sur l'utilisation de renumérotation de PYrevit.
Merci de votre aide.
Jacques.
﻿

```
ERROR [pyrevit.revit.db.transaction] Error in TransactionGroup Context. Rolling back changes. | <type 'exceptions.Exception'>:The input argument "categoryId" of function `anonymous-namespace'::ElementCategoryFilter_constructor or one item in the collection is null at line 230 of file d:\ship\2019_px64\source\revit\revitdbapi\gensrc\APIBuiltInElementFiltersProxy.cpp. 
Parameter name: categoryId

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\jriga\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\edit2.stack\ReNumber.pushbutton\script.py", line 307, in <module>
 File "C:\Users\jriga\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\edit2.stack\ReNumber.pushbutton\script.py", line 191, in pick_and_renumber
 File "C:\Users\jriga\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\edit2.stack\ReNumber.pushbutton\script.py", line 122, in get_elements_dict
 File "C:\Users\jriga\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\revit\db\query.py", line 261, in get_elements_by_categories
Exception: The input argument "categoryId" of function `anonymous-namespace'::ElementCategoryFilter_constructor or one item in the collection is null at line 230 of file d:\ship\2019_px64\source\revit\revitdbapi\gensrc\APIBuiltInElementFiltersProxy.cpp.
Parameter name: categoryId


Script Executor Traceback:
Autodesk.Revit.Exceptions.ArgumentNullException: The input argument "categoryId" of function `anonymous-namespace'::ElementCategoryFilter_constructor or one item in the collection is null at line 230 of file d:\ship\2019_px64\source\revit\revitdbapi\gensrc\APIBuiltInElementFiltersProxy.cpp.
Parameter name: categoryId
 à Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 à Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 à Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 à Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 à IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 à PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**Comment by eirannejad** [comment]
This is great. Thanks a lot. I'll look into it

**Comment by eirannejad** [comment]
Resolved and will be pushed with next release

**Comment by jrigal31** [comment]
Thank you.

 

Good job.

 

Best regards.

 

Jacques RIGAL

Directeur associé BIMoDIT | Consultant BIM 

Tél. : 06 10 23 35 75 | Email : jrigal@bimodit.fr <mailto:jrigal@bimodit.fr>  

 



Société conseil spécialiste du BIM

BIMoDIT, 2 impasse des Acacias, 31840 SEILH

 

 

 

De : Ehsan Iran-Nejad <notifications@github.com> 
Envoyé : vendredi 13 mars 2020 18:39
À : eirannejad/pyRevit <pyRevit@noreply.github.com>
Cc : jrigal31 <jrigal@outlook.fr>; Author <author@noreply.github.com>
Objet : Re: [eirannejad/pyRevit] Renumber Crash (#833)

 

Resolved and will be pushed with next release
