### ISSUE TITLE
Set Print Settings - Issue setting Print Setting for Variable Paper Size 

### ISSUE THREAD

**Issue by murd0cc** [eirannejad/pyRevit#853]
Hello,

I am having some issues when trying to Batch Print.
My issues start with trying to sheets of multiple sizes.

1. In the Print Sheets dialog, after selecting Variable Paper Size, there are some issues with Set Print Settings
2. Pressing the button does not opens a window that´s showing what seems to be an error log (up next)
3. Sometimes this also leads to crashes. In either case, it does not allow me to change the Print Setting for any of the sheets.
4. Another thing that got my attention was that a few sheets already have a print setting defined. But this cannot be changed.
5. Pressing the Print button only prints (as PDF, as this is the defined printer) only creates files for the sheets with a defined Print Setting.

Error 

```
> IronPython Traceback:
> Traceback (most recent call last):
>  File "C:\Users\Ionut\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Print Sheets.pushbutton\script.py", line 1133, in <module>
>  File "C:\Users\Ionut\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Print Sheets.pushbutton\script.py", line 1042, in set_sheet_printsettings
>  File "C:\Users\Ionut\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 746, in search_txt_changed
>  File "C:\Users\Ionut\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 674, in _list_options
>  File "C:\Users\Ionut\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 398, in show
>  File "C:\Users\Ionut\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 378, in __init__
>  File "C:\Users\Ionut\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 594, in _setup
>  File "C:\Users\Ionut\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 624, in _prepare_context
>  File "C:\Users\Ionut\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 637, in _update_ctx_groups
> TypeError: iteration over non-sequence of type NoneType
> 
> 
> Script Executor Traceback:
> IronPython.Runtime.Exceptions.TypeErrorException: iteration over non-sequence of type NoneType
>  at IronPython.Runtime.Operations.PythonOps.ThrowTypeErrorForBadIteration(CodeContext context, Object enumerable)
>  at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
>  at Microsoft.Scripting.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
>  at Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run5[T0,T1,T2,T3,T4,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
>  at Microsoft.Scripting.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
>  at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
>  at CallSite.Target(Closure , CallSite , Object , Object , SelectionChangedEventArgs )
>  at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
>  at _Scripting_(Object[] , Object , SelectionChangedEventArgs )
>  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>  at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>  at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>  at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
>  at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
>  at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
>  at System.Windows.Controls.Primitives.Selector.OnSelectedIndexChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
>  at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>  at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>  at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>  at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>  at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
>  at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
>  at CallSite.Target(Closure , CallSite , Object , Object )
>  at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
>  at IronPython.Runtime.Method.MethodBinding`1.SelfTarget(CallSite site, CodeContext context, Object target, T0 arg0)
>  at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
>  at Microsoft.Scripting.Interpreter.FuncCallInstruction`6.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
>  at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
>  at IronPython.Runtime.Method.MethodBinding.SelfTarget(CallSite site, CodeContext context, Object target)
>  at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
>  at Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run5[T0,T1,T2,T3,T4,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
>  at Microsoft.Scripting.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
>  at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run7[T0,T1,T2,T3,T4,T5,T6,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
>  at Microsoft.Scripting.Interpreter.FuncCallInstruction`9.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run9[T0,T1,T2,T3,T4,T5,T6,T7,T8,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
>  at CallSite.Target(Closure , CallSite , CodeContext , Object , Object , Object , Object , Object , Object )
>  at IronPython.Runtime.Types.PythonType.FastTypeSite`5.CallTarget(CallSite site, CodeContext context, Object type, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
>  at Microsoft.Scripting.Interpreter.DynamicInstruction`8.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run7[T0,T1,T2,T3,T4,T5,T6,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
>  at Microsoft.Scripting.Interpreter.FuncCallInstruction`9.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run11[T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10)
>  at System.Dynamic.UpdateDelegates.UpdateAndExecute10[T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
>  at Microsoft.Scripting.Interpreter.DynamicInstruction`11.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run10[T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
>  at System.Dynamic.UpdateDelegates.UpdateAndExecute9[T0,T1,T2,T3,T4,T5,T6,T7,T8,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
>  at Microsoft.Scripting.Interpreter.DynamicInstruction`10.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
>  at IronPython.Compiler.PythonCallTargets.OriginalCallTarget3(PythonFunction function, Object arg0, Object arg1, Object arg2)
>  at CallSite.Target(Closure , CallSite , Object , Object , RoutedEventArgs )
>  at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
>  at _Scripting_(Object[] , Object , RoutedEventArgs )
>  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>  at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>  at System.Windows.Controls.Primitives.ButtonBase.OnClick()
>  at System.Windows.Controls.Button.OnClick()
>  at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
>  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>  at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>  at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>  at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
>  at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>  at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>  at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>  at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>  at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>  at System.Windows.Input.InputManager.ProcessStagingArea()
>  at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>  at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>  at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>  at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>  at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>  at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>  at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>  at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>  at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>  at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>  at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>  at System.Windows.Window.ShowHelper(Object booleanBox)
>  at System.Windows.Window.ShowDialog()
>  at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
>  at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>  at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
>  at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
>  at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

```

**Desktop (please complete the following information):**
 - OS: Windows 7
 - pyRevit Version [e.g. 4.7.4]
 - pyRevit Environment: 

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Ionut>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.4" | Path: "C:\
Users\Ionut\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2020" | Engine: 277 | Path: "C:\Users\Ionut\Ap
pData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Ionut\AppData\Roaming\Autode
sk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2020 First Customer Ship" | Engine: 277 | Path: "C:\Users\Ion
ut\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Ionut\AppData\Roaming\A
utodesk\Revit\Addins\2020\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Ionut\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2020 | Version: 20.2.0.48 | Build: 20191031_1115(x64) | Language:
 1033 | Path: "C:\Program Files\Autodesk\Revit LT 2020"
2020 First Customer Ship | Version: 20.0.0.377 | Build: 20190327_2315(x64) | Lan
guage: 1033 | Path: "D:\Program Files\Autodesk\Revit 2020"
==> Running Revit Instances
PID: 13364 | 2020 First Customer Ship | Version: 20.0.0.377 | Build: 20190327_23
15(x64) | Language: 0 | Path: ""
==> User Environment
Microsoft Windows 7 [Version 6.1.7601]
Executing User: GONZALES\Ionut
Active User: GONZALES\Ionut
Admin Access: No
%APPDATA%: "C:\Users\Ionut\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.17.0.0

C:\Users\Ionut>
```

Thank you
![PrintSettingMenu](https://user-images.githubusercontent.com/62068271/76439895-c602c980-63c5-11ea-830c-7841d0917229.JPG)

**Comment by eirannejad** [comment]
pyRevit tries to determine the appropriate print setting type for each sheet and that's why some of the sheets have settings already applied. You can change those however.

Would you be able to share an example model so I can test why the **Set Print Settings** does not open a window?

**Comment by murd0cc** [comment]
Hello,

Where does pyRevit read that information from? How do I set the appropriate print settings ?

I have attached a sample model with the same symptoms.
**_Warning_**:
First attempt turns to **Set Print Settings** out the error. Second attempt crashes Revit.

Thank you very much,

[pyRevit Troubleshooting_blank.zip](https://github.com/eirannejad/pyRevit/files/4342587/pyRevit.Troubleshooting_blank.zip)

**Comment by eirannejad** [comment]
@murd0cc So I opened the model and tested out the print settings. It seems to be working fine. The print settings are stored in Revit's internal print settings window. See the GIF below

![n4F97lleHo](https://user-images.githubusercontent.com/8197916/76874681-c61f2100-682c-11ea-950d-bb750241e1d1.gif)

**Comment by murd0cc** [comment]
That would mean the issue has something to do with my version of Revit. Right? 
Any idea where I should start looking ? 

Thanks alot for helping out!

**Comment by eirannejad** [comment]
No idea to be honest. Which Revit version are you running?! Would you mind sending me a gif of how the error happens exactly?

**Comment by murd0cc** [comment]
Revit
20.0.0.377
20190327_2315(x64)
running under Windows 7

![batch print troubleshooting](https://user-images.githubusercontent.com/62068271/76876757-1329e400-687b-11ea-8e6c-928d4f7efef5.gif)

**Comment by eirannejad** [comment]
Great. This helps. Lemme dig deeper

**Comment by eirannejad** [comment]
Hey would you mind testing pyRevit 4.7.5? I have done some previous improvements to this function and wanted to know if that would resolved this issue. I'm still making improvements and will push with 4.7.6 soon

**Comment by murd0cc** [comment]
Hey there. I tried 4.7.5. You were right, it's fixed. I tried it on two original files where that issue occurred, and also on a different PC. They all performed as expected, and allowed me to set the individual print settings.

Thank you very much and sorry for bothering you for this less.

Keep up the good work, and stay in good health :)

**Comment by eirannejad** [comment]
Absolutely. I didn't realize at first that I had fixed a few related issues before and looking through the code, I couldn't see the bug. Then going through the commits to write the release notes for 4.7.5 I realized there has already been changes to this.

I'm glad it is fixed. This issue helped improve a few other things so it's all for a good cause :)
