### ISSUE TITLE
RevitPythonShell script works but in pyRevit it doesn't

### ISSUE THREAD

**Issue by yafimski** [eirannejad/pyRevit#907]
Hi,
I wrote a working script and ran it in RevitPythonShell.

```
from Autodesk.Revit.DB import FilteredElementCollector, BuiltInCategory
from collections import OrderedDict
from Autodesk.Revit.DB import Transaction

doc = __revit__.ActiveUIDocument.Document

def create_gridline_dims(gridDict):
	ptArray = ReferenceArray()
	ptList = []
	gridDict = OrderedDict( sorted(gridDict.items(),key=lambda x: x[1], reverse=False) )
	gridlines = gridDict.keys()

	for g in gridlines:
		ptList.Add(doc.GetElement(g).GetExtents().MinimumPoint)
		temp = doc.GetElement(g)
		ptArray.Append( Reference(temp) )

	refLine = Line.CreateBound(ptList[0], ptList[-1])
	print(type(refLine))
	gridDimension = doc.Create.NewDimension(doc.ActiveView, refLine, ptArray)

numgrids = {}
chargrids = {}
grid_collector = FilteredElementCollector(doc) \
					.OfCategory(BuiltInCategory.OST_Grids) \
					.WhereElementIsNotElementType() \
					.ToElements()

for grid in grid_collector:
    if grid.Name.isdigit():
    	numgrids.Add(grid.Id, grid.Name)
    else:
    	chargrids.Add(grid.Id, grid.Name)


t = Transaction(doc, "Create Grid Dimensions")
t.Start()
create_gridline_dims(numgrids)
create_gridline_dims(chargrids)

t.Commit()
```

In RevitPythonShell, the gridline dimensions are created. No problem.
But when I reload by pyRevit extension toolbar, the following errors appears:

> A transaction or sub-transaction was opened but not closed. All changes to the active document made by External Command will be discarded.

as well as (in the shell window of my extension):

> IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\yafim\AppData\Roaming\pyRevit-Master\extensions\AH_Tools.extension\AH_Tools.tab\Tools.panel\AutoDims.pushbutton\script.py", line 51, in <module>
 File "C:\Users\yafim\AppData\Roaming\pyRevit-Master\extensions\AH_Tools.extension\AH_Tools.tab\Tools.panel\AutoDims.pushbutton\script.py", line 10, in create_gridline_dims
NameError: global name 'ReferenceArray' is not defined
Script Executor Traceback:
IronPython.Runtime.UnboundNameException: global name 'ReferenceArray' is not defined
 at IronPython.Runtime.Operations.PythonOps.GetVariable(CodeContext context, String name, Boolean isGlobal, Boolean lightThrow)
 at IronPython.Compiler.LookupGlobalInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

I'm guessing that the ReferenceArray is null and is messing up the Transaction process, but I can't figure out how to define the ReferenceArray properly.

Any ideas?

**Comment by htlcnn** [comment]
You did not import ReferenceArray

**Comment by yafimski** [comment]
Ah, okay thanks, I wasn't aware I skipped that import. Hard to remember to import everything individually. Would you recommend import * from DB?

**Comment by htlcnn** [comment]
That's not recommended by default. You could wrap them in multiple lines
using parentheses. Eg:
from Autodesk.Revit.DB import (
    XYZ,
    ReferenceArray,
    ...)
