### ISSUE TITLE
Sheet maker issue

### ISSUE THREAD

**Issue by rvzenteno** [eirannejad/pyRevit#929]
**Describe the bug**
I'm able to type the sheets that I want to create with the sheet maker. in this particular case i have 71 sheets. after I press the Create button it just pulls the pyRevit Console. I've used this before and after entering the sheet it would ask what titleblock to use but it does not go to that step.
Thank you.

**Expected behavior**
Create the Sheets in the Project Browser

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.7.6:277:2020.2
 - pyRevit Environment: 

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.6" | Path: "C:\Users\rober\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021 First Customer Ship" | Engine: 277 | Path: "C:\Users\rober\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\rober\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
master | Product: "Autodesk Revit 2020" | Engine: 277 | Path: "C:\Users\rober\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\rober\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\rober\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\rober\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2018 First Customer Ship" | Engine: 277 | Path: "C:\Users\rober\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\rober\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\rober\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021"
Autodesk Revit 2020 | Version: 20.2.20.31 | Build: 20200426_1515(x64) | Language: 1033 | Path: "E:\Program Files\Autodesk\Revit 2020"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
2018 First Customer Ship | Version: 18.0.0.420 | Build: 20170223_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

**Additional context**
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\rober\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Sheets.pulldown\Batch Sheet Maker.pushbutton\script.py", line 108, in <module>
 File "C:\Users\rober\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Sheets.pulldown\Batch Sheet Maker.pushbutton\script.py", line 87, in create_sheets
 File "C:\Users\rober\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Sheets.pulldown\Batch Sheet Maker.pushbutton\script.py", line 38, in _process_sheet_code
ValueError: too many values to unpack


Script Executor Traceback:
IronPython.Runtime.Exceptions.ValueErrorException: too many values to unpack
 at IronPython.Runtime.Operations.PythonOps.GetEnumeratorValuesFromList(List list, Int32 expected)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Runtime.Method.MethodBinding.SelfTarget(CallSite site, CodeContext context, Object target)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at IronPython.Compiler.PythonCallTargets.OriginalCallTarget3(PythonFunction function, Object arg0, Object arg1, Object arg2)
 at CallSite.Target(Closure , CallSite , Object , Object , RoutedEventArgs )
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at _Scripting_(Object[] , Object , RoutedEventArgs )
 at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
 at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
 at System.Windows.Controls.Primitives.ButtonBase.OnClick()
 at System.Windows.Controls.Button.OnClick()
 at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
 at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
 at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
 at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
 at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
 at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
 at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
 at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
 at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
 at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
 at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
 at System.Windows.Input.InputManager.ProcessStagingArea()
 at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
 at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
 at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
 at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
 at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
 at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
 at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
 at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
 at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
 at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
 at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
 at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
 at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
 at System.Windows.Window.ShowHelper(Object booleanBox)
 at System.Windows.Window.ShowDialog()
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**Comment by eirannejad** [comment]
Would you mind sharing an example of what you are trying to do and a screenshot of the pyRevit console errors?

**Comment by rvzenteno** [comment]
Sure thing. 

Below is the list 

![image](https://user-images.githubusercontent.com/600617/87327042-8da10280-c501-11ea-8088-a124ed286527.png)

After I Press Create

The following window opens up

![image](https://user-images.githubusercontent.com/600617/87327110-a4dff000-c501-11ea-846c-928f56c2c06e.png)

the complete text of this window is shown on my original post after "Script Executor Traceback:"

**Comment by alexdaversa** [comment]
@rvzenteno Can you confirm that there is a tab between "M 1.05A" and "LEVEL 5" and also a tab between "LEVEL 5" and "UNITS SECTION A" so two tabs on each line of entry? The tool will not work if this is the case, as it only accepts one tab per line.

**Comment by rvzenteno** [comment]
@alexdaversa sorry for not replying sooner i had a surgery and I'm just getting back on track. you are correct I had a secondary tab. Thank you.

![image](https://user-images.githubusercontent.com/600617/88993841-04d1e700-d2b5-11ea-8f88-6cae82fa6ab6.png)

**Comment by rvzenteno** [comment]
@alexdaversa sorry for not replying sooner i had a surgery and I'm just getting back on track. you are correct I had a secondary tab. Thank you.

![image](https://user-images.githubusercontent.com/600617/88993841-04d1e700-d2b5-11ea-8f88-6cae82fa6ab6.png)
